### ISSUE TITLE
RunnerOptionStore constructor argument `conf_paths` cannot take string despite the docs indicating it can

### ISSUE THREAD

**Issue by asottile** [Yelp/mrjob#1039]
https://github.com/Yelp/mrjob/blob/4a66b1c0ee12d540b2e3d6f43391cae6b9bc6ca1/mrjob/runner.py#L149-L150

**Comment by davidmarin** [comment]
Thanks, will look into it!

**Comment by davidmarin** [comment]
Okay, cool. Do you have a use case where it would be helpful for this constructor to take a string? If not, I'm probably going to just fix the comment.

**Comment by asottile** [comment]
I'm currently working around this as follows:

```python
        conf_filename = os.environ.get('MRJOB_CONF_FILE', '/etc/mrjob.conf')
        emr_config = EMRRunnerOptionStore('emr', [], (conf_filename,))
```

**Comment by davidmarin** [comment]
Huh. Why `$MRJOB_CONF_FILE`? mrjob will do just what you're doing automatically with `$MRJOB_CONF`.

**Comment by asottile** [comment]
@davidmarin that line's not entirely important, it's for a test

**Comment by davidmarin** [comment]
Got it.

Okay, my opinion is that your use case doesn't justify making mrjob more complicated, so will just update the comment. Thanks!

**Comment by davidmarin** [comment]
Ah, just noticed that the name of the argument to `EMRRunnerOptionStore` is `conf_path` when it should be `conf_paths`. Fixing that.
