### ISSUE TITLE
--no-check-input-paths option not working

### ISSUE THREAD

**Issue by okomestudio** [Yelp/mrjob#1046]
The configuration option `--no-check-input-paths` does not appear working for the EMR runner. The EMR runner always try to check the input S3 URIs even if the option is supplied.

Glancing through the code, it looks like the following lines

https://github.com/Yelp/mrjob/blob/master/mrjob/launch.py#L570-L572

need to also include the hadoop_emr_opt_group, as in:

```
    def emr_job_runner_kwargs(self):
        ...
        return combine_dicts(
            self.job_runner_kwargs(),
            self._get_kwargs_from_opt_group(self.hadoop_emr_opt_group),
            self._get_kwargs_from_opt_group(self.emr_opt_group))
```

Once this change is made, the option properly works with the EMR runner.

I haven't thoroughly checked if the above is the proper solution, but if it is, then the same line needs to be added to the method `emr_job_runner_kwargs` as well.

**Comment by alejandro-rivera** [comment]
I was also getting bitten by this.

Pull request #1049 fixes the issue for both Hadoop and EMR runners.

Cheers.
