### ISSUE TITLE
can load same conf file twice

### ISSUE THREAD

**Issue by asottile** [Yelp/mrjob#1047]
Consider the following:
- 2 config files: a.conf, b.conf
- b.conf has include: a.conf
- a.conf specifies bootstrap_actions

An invocation as follows:

`python test.py -c a.conf -c b.conf`

Will lead to the bootstrap_actions in a.conf being doubled

A simple workaround is to just not do that.

**Comment by davidmarin** [comment]
Doc, it hurts when I do this... :)

Yeah, this counts as a bug; I can't see any reason why someone would want to load the same config file twice. v0.5.0 is pretty full and there's an easy workaround, so putting this "on the radar" for now.

**Comment by davidmarin** [comment]
Pretty sure this is fixed.
