### ISSUE TITLE
Make add_file_option accept an options group like add_passthrough_option

### ISSUE THREAD

**Issue by justincinmd** [Yelp/mrjob#1060]
The MRJob method `add_passthrough_option` has a kwarg `opt_group` which enables the caller to set the option group for the passthrough option. This is useful to group options so they can be accessed programmatically in batches that wrap mrjobs. 

The related method `add_file_option` does not have this kwarg, which makes it difficult to pass through file options to batches.

**Comment by davidmarin** [comment]
Good point!

**Comment by davidmarin** [comment]
(If you're blocked on this, feel free to make a pull request; should be pretty straightforward.)

**Comment by davidmarin** [comment]
mrjob no longer does option groups since switching to `argparse` in v0.6.0.
