### ISSUE TITLE
pool_wait_minutes from .mrjob.conf ignored

### ISSUE THREAD

**Issue by alanhdu** [Yelp/mrjob#1070]
In our `.mrjob.conf`, we set `pool_wait_minutes: 10`. But unless we pass in the command-line flag `--pool-wait-minutes 10`, mrjob doesn't bother waiting.

I think it's because the default command line option for `--pool-wait-minutes` is 0, which overwrites the option read from `.mrjob.conf` (other defaults are set to `None`, so https://github.com/Yelp/mrjob/blob/master/mrjob/conf.py#L261 catches that).

**Comment by davidmarin** [comment]
Whoops. Will try to fix that for v0.5.0.

**Comment by davidmarin** [comment]
Going to try to backport this to 0.4.6
