### ISSUE TITLE
Add a parallel version of local runner

### ISSUE THREAD

**Issue by andyfoundi** [Yelp/mrjob#1083]
The current LocalMRJobRunner creates multiple workers for mapper/reducer tasks.
However, these separate tasks are actually running in serial such that the processes are chained together using pipe. In other words, it doesn't utilize the number of CPU cores in the local machine.
It makes sense for LocalMRJobRunner since the purpose is for debugging.

The problem is that sometimes the data is not that huge, but it still takes a couple hours to process with a single processor. Setting up a Hadoop cluster is overkilled but we really hope mrjob could utilize the CPU power of my 64-core machine. Instead of choosing other python-based framework we really hope to stay with mrjob for all our data processing, large data to small data so we can reuse our knowledge and codebase.

Is it possible to either add multi-process support to existing  LocalMRJobRunner or add another variant of local runner that utilizes mult-core CPU? 

thanks
Andy

**Comment by davidmarin** [comment]
Nice, I've certainly thought about having local mode work as a poor man's Hadoop, but no one else has really articulated the use case.

It's not really a priority right now (trying to get caught up with Python 3 and YARN), but it's certainly do-able. Would you be willing to take a stab at it?

**Comment by andyfoundi** [comment]
Hi David,
Sounds interesting.
Any thought, advise or suggestion on how this could be done? For example, I
think it makes sense to have a separate runner as the local runner is for
debugging.
2015年7月22日 上午6:37於 "David Marin" <notifications@github.com>寫道：

**Comment by alejandro-rivera** [comment]
Hey andyfoundi.

There's already an `inline` runner used for debugging purposes, iirc.

Perhaps a `--parallel` switch could be added to the local runner for this new functionality to be active? or maybe forcing the parallelization is the way to go.

In any case, this would certainly be a nice addition to mrjob, given that sometimes you need to write MapReduce Jobs that certainly don't need all the power that a Hadoop cluster provides, yet you'd like them to take full advantage of all the cores in a single machine when using the `local` runner.

**Comment by davidmarin** [comment]
@andyfoundi, I wouldn't make a new kind of runner. The `local` runner already is parallel, it just kind of sucks at it right now. You could make it suck less and it would still be as useful for debugging.

**Comment by AndreLouisCaron** [comment]
I'm also interested in this!

**Comment by andyfoundi** [comment]
Awesome! Thanks
