### ISSUE TITLE
mapper_pre_filter is triggering java.lang.RuntimeException

### ISSUE THREAD

**Issue by NicolasEhrhardt** [Yelp/mrjob#1126]
I am running a job on a file containing very large json text. I need to filter out some lines since not all of them are relevant and I don't want the mapper to spend too much time parsing it when it's not a relevant entry.

Rather than discarding them in the mapper, it seemed like a good job for [`mapper_pre_filter`](http://mrjob.readthedocs.org/en/latest/guides/writing-mrjobs.html#cmd-filters): I am using something similar to `grep pattern`. Unfortunately, when using it, all mappers are throwing `RuntimeException`.

> java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
>     at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:372)
>     at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:586)
>     at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:136)
>     at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:63)
>     at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:36)
>     at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:441)
>     at org.apache.hadoop.mapred.MapTask.run(MapTask.java:377)
>     at org.apache.hadoop.mapred.Child$4.run(Child.java:259)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at javax.security.auth.Subject.doAs(Subject.java:415)
>     at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1140)
>     at org.apache.hadoop.mapred.Child.main(Child.java:253)

I am assuming that's an issue with how piping is done for filtering entries before the mapper. (The job is running well without that prefilter).

**Comment by davidmarin** [comment]
Probably is! What version of Hadoop are you using?

**Comment by davidmarin** [comment]
Shoot, without more details (e.g. what your `grep` command line was), I can't duplicate this bug. Closing for now.

**Comment by aeeilllmrx** [comment]
I am getting this issue as well. Would like to filter out certain lines from json file before the mapper step.

**Comment by davidmarin** [comment]
Okay, I suspect this has something to do with how YARN handles pipes (or if they're allowed at all).

Going to try to get the 0.5 release out before circling back to this. Any more details you can provide would be helpful.

**Comment by davidmarin** [comment]
Huh, the documentation says that you can't use pipes in mappers (both in [1.2.1](https://hadoop.apache.org/docs/r1.2.1/streaming.html#Can+I+use+UNIX+pipes%3F) and [2.7.1](http://hadoop.apache.org/docs/r2.7.2/hadoop-streaming/HadoopStreaming.html#Can_I_use_UNIX_pipes)).

This certainly worked at one point long long ago (we used it for a workaround for versions of Hadoop that were so old they didn't support combiners). Seems like the fix is to make `sh -c "<pre cmd> | <script cmd>"` the argument to `-mapper` etc.

**Comment by davidmarin** [comment]
Oh, wait, it looks like we already do the above (look for `bash_wrap()` in `mrjob/hadoop.py`).

The use of `bash` is hard-coded, so it might be that `bash` isn't in the path on your system? (Really, we should be using `sh_bin`.) Also possibly `grep` isn't in the path, or is otherwise unavailable?

**Comment by aeeilllmrx** [comment]
I'll try again this coming week and let you know!

**Comment by davidmarin** [comment]
@aeeilllmrx, what happened?

**Comment by davidmarin** [comment]
If this is actually broken, hopefully #1330 fixes this. Slating this for the next release.

**Comment by davidmarin** [comment]
Oh, you know, Hadoop 1 always logs `java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code <N>` to stderr when a task fails. You don't have error messages other than that?

**Comment by aeeilllmrx** [comment]
@davidmarin sorry for leaving you in the dark- i'll check this week but i think we can close this

**Comment by davidmarin** [comment]
Okay, it looks like a few things are wrong with pre-filters (see #1521, #1522, #1524), so that's probably what caused this.
