### ISSUE TITLE
Python3 bug when executing with hadoop

### ISSUE THREAD

**Issue by pdonorio** [Yelp/mrjob#1142]
Hello,
i downloaded the latest dev because i want to use the project with python3.

Everything works for now, except when i launch with Hadoop.

I am using an empty template just to show the error:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
""" MapReduce easily with Python """

from mrjob.job import MRJob
from mrjob.step import MRStep

class job(MRJob):
    def mapper(self, _, line):
        pass
    def reducer(self, key, line):
        pass
    def steps(self):
        return [ \
            MRStep(mapper=self.mapper, reducer=self.reducer), \
        ]

if __name__ == "__main__":
    job.run()
```

When i launch with 
`$ python myscript.py -r hadoop sometext.txt`
i get the following output

```
Unexpected option hdfs_tmp_dir
no configs found; falling back on auto-configuration
no configs found; falling back on auto-configuration
creating tmp directory /tmp/automatic_script.root.20151005.115007.652927
writing wrapper script to /tmp/automatic_script.root.20151005.115007.652927/setup-wrapper.sh
Traceback (most recent call last):
  File "myscript.py", line 19, in <module>
    job.run()
  File "/opt/mrjob/mrjob/job.py", line 433, in run
    mr_job.execute()
  File "/opt/mrjob/mrjob/job.py", line 451, in execute
    super(MRJob, self).execute()
  File "/opt/mrjob/mrjob/launch.py", line 160, in execute
    self.run_job()
  File "/opt/mrjob/mrjob/launch.py", line 227, in run_job
    runner.run()
  File "/opt/mrjob/mrjob/runner.py", line 450, in run
    self._run()
  File "/opt/mrjob/mrjob/hadoop.py", line 229, in _run
    self._upload_local_files_to_hdfs()
  File "/opt/mrjob/mrjob/hadoop.py", line 256, in _upload_local_files_to_hdfs
    self._mkdir_on_hdfs(self._upload_mgr.prefix)
  File "/opt/mrjob/mrjob/hadoop.py", line 265, in _mkdir_on_hdfs
    hadoop_version = self.get_hadoop_version()
  File "/opt/mrjob/mrjob/hadoop.py", line 215, in get_hadoop_version
    first_line = stdout.split('\n')[0]
TypeError: 'str' does not support the buffer interface
```

The problem is in the strings parsing to get the hadoop version.
I found a workaround changing `mrjob/hadoop.py` with two changes:

1. line 60: `HADOOP_VERSION_RE = re.compile(br'^.*?(?P<version>(\d|\.)+).*?$')` removing the b for Byte
2. line 215: `first_line = stdout.split('\n')[0]` apply `decode()` to the stdout string

Thanks you all for your great work,
Paolo

**Comment by davidmarin** [comment]
Yeah, or `split()` could use `b'\n'` instead of `'\n'`. :)

Thank you for catching this! I guess the automated tests for the Hadoop runner need to be improved. Planning to look at this and other Hadoop runner issues later this week.

**Comment by pdonorio** [comment]
> or split() could use b'\n' instead of '\n'

I tried that first, and got other problems with bytes on the very next group matching.

Thanks for the quick response :)

**Comment by davidmarin** [comment]
Aha, the test cases weren't catching this because the mock Hadoop binary wasn't returning anything for the version command.

**Comment by davidmarin** [comment]
Ah, because `hadoop version` writes to stderr, and we were checking stdout. D'oh!

**Comment by davidmarin** [comment]
Okay, this should be fixed in `master`. Try it out!

**Comment by pdonorio** [comment]
Hello, 
i just pulled the master and the problem's gone.

Thanks a lot!
Paolo
