### ISSUE TITLE
Make terminate_idle_job_flow.sh support other yarn jobs (e.g. spark)

### ISSUE THREAD

**Issue by mikekap** [Yelp/mrjob#1145]
It's currently possible to run jobs on yarn directly (via script-runner.jar), but terminate_idle_job_flow seems to ignore anything running on yarn directly. It would be nice to also check `yarn application -list | grep -v 'Total number' | grep -q RUNNING` if anything is running.

**Comment by davidmarin** [comment]
Good point. That seems pretty straightforward; I'll see if I can work it in.

**Comment by davidmarin** [comment]
@mikekap This is now in `master` (see #1151). The only hand-testing I did was with Hadoop though; would you mind verifying that clusters won't terminate while they're running Spark?

I used `--max-hours-idle 0.00001 --mins-to-end-of-hour 60` to guarantee that the cluster would terminate as soon as it became idle.
