### ISSUE TITLE
override included conf files

### ISSUE THREAD

**Issue by VictoriaTGu** [Yelp/mrjob#1156]
This is a sketch of the use case: I have a base configuration file that has my AWS access key ID's that are updated every so often, and it also has some minimum configuration settings. This base file is inherited by multiple other configuration files that have more specific information for different types of jobs. I would like to be able to override a few configurations in the base configuration (namely the AWS access keys).

base.conf
-------------
emr:
- aws_access_key_id: ...
- aws_secret_access_key: ...
- ami_version: 1.0.0

inherits_base.conf
------------------------
include 'base.conf'
emr:
- ami_version: 1.1.0 # override ami_version: 1.0.0

**Comment by davidmarin** [comment]
This is theoretically a "breaking" change, but it's closer to the intended behavior (see the examples in #104).

**Comment by davidmarin** [comment]
Never mind, this is actually the current behavior.

There are unit tests for this, but they're not where you'd expect: `test.test_option_store.MultipleConfigFilesValuesTestCase`, not `tests.test_compat`.
