### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by lordnynex** [Yelp/mrjob#1157]
Is it safe-ish to run the dev branch in production? I was looking at the milestones last night and there doesn't seem to be a date but I really need the emr-release functionality for spark. For the foreseeable future it will just be running normal map reduce jobs, but I want to put the spark setup in ahead of time. 

Also, some of the config file directives relating to bootstrap are a little confusing to me. I think the confusion stems from the amazon docs being a bit disjointed. Additionally, I'm somewhat new to EMR/hadoop/*. Apologies if these are dumb questions.

- To setup spark, is the intention to use 'emr_api_params' for 'NewSupportedProducts.member.N' documented at http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_RunJobFlow.html ?
- Now that I'm rereading the EMR runner docs at http://mrjob.readthedocs.org/en/latest/guides/emr-opts.html It seems thats emr_api_params is not new to 5.0, so can I accomplish the same thing with setting ami_version to 3.7.0? 
- It would be really great if there was more config/lifecycle examples. Particularly around spark. If I can get the above running, do I need to specify a bootstrap action to install pyspark or do you happen to know if the AWS AMI has this in site packages just by installing spark? 
- I've noticed that some strange behavior with ec2_key_pair_file. I think the issue is the general complexity of my ~/.ssh/config file but it seems no matter what I do, I'm being prompted for key passphrase on one of my other private keys which makes it seem like ec2_key_pair_file is not being honored. Is there any way to pass ssh args? 
- In my case, I'd really like to launch the runner into a VPC that has a designated bastion host so ec2_key_pair_file is really only needed for the ssh tunnel. It would be really great for me if I could specify a path to an authorized_keys file that would be automatically forwarded. It would really remove ssh complication. 

As a small note, there is duplicate documentation for emr_tag in the 5.0 documentation at http://mrjob.readthedocs.org/en/latest/guides/emr-opts.html

**Comment by lordnynex** [comment]
Also, are there any known adapters/bridges for starcluster?
Also also, Is it possible to programmatically define mrjob.conf opts? I see examples for running the runner, but currently I have to set a bunch of ENV vars before executing the runner to point to the proper conf. It seems like it would be a lot more convenient to pass a configuration object.

**Comment by davidmarin** [comment]
Yes, the dev branch is safe-ish; `mrjob` has a ton of unit tests.

I unfortunately don't know much about Spark. It should be possible to use mrjob to launch a cluster that supports Spark, but it may not provide much value over the [AWS CLI](https://aws.amazon.com/cli/). 
If you have any ideas about how mrjob might integrate with spark (`MRSpark`?), I'd love to hear them.

You can pass ssh args by setting `ssh_bin`: http://mrjob.readthedocs.org/en/latest/guides/emr-opts.html#ssh-access-and-tunneling. 

Information about launching into a custom VPC is [here](http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-plan-vpc-subnet.html). mrjob doesn't currently have an `--ec2-attributes` switch (see the CLI section), but if you'd like me to add one; just let me know. I'd have to look at the AWS CLI source, but I suspect it uses the `AdditionalInfo` API param.

There isn't currently an adapter for StarCluster other than the Hadoop runner. Hadoop runner support is getting a lot better in v0.5.0/master. There's a good argument for making the Hadoop runner able to work over SSH; the relevant ticket is #990.

To define mrjob opts programmatically, just pass them directly as keyword options to the appropriate subclass of `MRJobRunner`. You can see an explanation of the non-option keyword arguments (such as `mr_job_script`) [here](http://mrjob.readthedocs.org/en/latest/runners-runner.html#mrjob.runner.MRJobRunner.__init__).
