### ISSUE TITLE
ssh terminal issues

### ISSUE THREAD

**Issue by lordnynex** [Yelp/mrjob#1161]
Hello,

I'm still having a few issues with specifying ssh key path. Because ssh prompts for key passphrase (because ssh is not forwarding the key specified in mrjob.conf), the terminal gets left in noecho state. Although it's not a mrjob issue specifically, it would be very nice if os.term("stty echo") could happen right before exit. 

For general info, users who may find this in the future, if you're prompted by ssh for key passphrase, you'll likely need to run 'reset' on your terminal after a run with failed tunnel. 

Feel free to close

**Comment by davidmarin** [comment]
This sounds like a confusing user experience. I think we could fix this by running `ssh` with `-n`.
