### ISSUE TITLE
Counters are not refreshed when same job flow id is reused in emr

### ISSUE THREAD

**Issue by sayantansatpati** [Yelp/mrjob#1164]
I am using mrjob iteratively, using a driver(emr runner), for graph processing. It re-uses the same job flow id (--pool-emr-job-flows) so that a new emr cluster is not created every time. The issue is that runner.counters() keeps getting the counters from Step-1, or for the first iteration only. However, the following gets all counters from all steps, but there is extra work to parse the file:

python -m mrjob.tools.emr.fetch_logs --counters ${JOB_FLOW_ID}

**Comment by davidmarin** [comment]
I think that's the intended behavior. In your case, you only have one kind of job in your pool, but in most cases, jobs on the same pooled job flow won't be related at all, and aren't interested in each others' counters.

**Comment by sayantansatpati** [comment]
How do we then deal with counters for programs that execute the same MRJob repeatedly (Graph Processing, K-Means etc) & are controlled by an external driver/runner? The reason we re-use the same job flow id is because we don't want to spawn a new cluster at every iteration. Is there any alternate way of handling counters in such scenarios, which are incidentally very common?
