### ISSUE TITLE
Reusing the same EC2 instance in between changes to 'setup' steps

### ISSUE THREAD

**Issue by alexanderkoumis** [Yelp/mrjob#1169]
Jobs are being pooled, but it seems like when I modify a 'setup' step, an existing job flow is used but the initial setup steps are being executed. I could be wrong but this is what I gathered from pouring through resulting log files. The result is that every time I need to modify a setup step, I terminate the existing cluster and start the job again.

The EC2 provisioning step then introduces a hefty delay (which becomes unbearable after starting 74 clusters in the span of a few days to debug a few shell commands). Running with `-r local` instead of `-r emr` helped debugging the logic of my map/reduce stages but does not provide an isolated build environment. Just a little context, I need to use the cv2 (OpenCV) Python module and ended up compiling the library for AMI 3.10, saving the libraries to a s3 bucket, placing them into the proper directories upon setup time (also would appreciate if anyone has optimization suggestions, doing this in the setup step to get access to `export`):

```yaml
setup:
    wget http://facedata.s3.amazonaws.com/OpenCV-unknown-x86_64.tar.gz && sudo tar -xzvf ./OpenCV-unknown-x86_64.tar.gz -C /usr/local
    export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.6/dist-packages/
```

**Comment by davidmarin** [comment]
Sorry, explain to me why you're not using `bootstrap` to compile OpenCV?

**Comment by alexanderkoumis** [comment]
For one I already precompiled it and I'd rather not wait to do so again if I have to change a bootstrap step. I did just try placing the `wget` step in `bootstrap` and it worked out fine. I guess the core of what I'm curious about is whether or not using different `setup` scripts with the same job flow is supposed to run the new scripts rather than the initial ones?

**Comment by davidmarin** [comment]
They definitely can. Pooling doesn't care about `setup` steps.

If you're using `setup` in a way that could affect future steps (like you're doing with `/usr/local` above), just be aware that you're bending the rules, and think hard about what the effect might be. (EMR doesn't run steps in parallel, so you don't have to worry about past steps, just future ones.) In your case, I think it'd make more sense to un-tar OpenCV in the current directory and point ``PYTHONPATH`` at it there (``export PYTHONPATH=$PYTHONPATH:./...``).

**Comment by davidmarin** [comment]
Also, if you need your tarball to be non-public, you can put it in a non-public bucket on S3 and use the `hadoop fs` command:

```
hadoop fs -get s3://bucket/path/to/OpenCV.tar.gz OpenCV.tar.gz
```
