### ISSUE TITLE
inaccurate warning for option bootstrap_cmd...?

### ISSUE THREAD

**Issue by toomanycats** [Yelp/mrjob#1178]
I'm new to mrjob and  using a config file with "bootstrap_cmd:" in it and it generates this warning:
Got unexpected opts from mrjob_config.conf: bootstrap_cmd

Switching the syntax to "bootstrap:" generates no warning, but the boot strap then fails.

Is this a buggy warning ?

**Comment by davidmarin** [comment]
The option is named `bootstrap_cmds`.

Not sure why `bootstrap` failed; I'd have to see your config file.

**Comment by toomanycats** [comment]
Thanks David for clarifying the syntax. I'm trying again with corrected conf file and it if fails will post it.
