### ISSUE TITLE
Configuration option for increasing instance volume size

### ISSUE THREAD

**Issue by alexanderkoumis** [Yelp/mrjob#1180]
Using mrjob to build CUDA drivers and subsequently install GPU-enabled OpenCV on g2.2xlarge instances. However, the installation files are rather large, and bootstrapping fails due to lack of space on the device:

```bash
+ chmod +x /home/hadoop/nvidia/cuda_7.5.18_linux.run /home/hadoop/nvidia/NVIDIA-Linux-x86_64-352.55.run
+ /home/hadoop/nvidia/cuda_7.5.18_linux.run -extract=/home/hadoop/nvidia
cp: error writing /home/hadoop/nvidia/cuda-samples-linux-7.5.18-19867135.run: No space left on device
cp: failed to extend /home/hadoop/nvidia/cuda-samples-linux-7.5.18-19867135.run: No space left on device
```

Was wondering if there is any configuration option for mrjob to increase the default volume size?

Thanks,
Alexander K

**Comment by alexanderkoumis** [comment]
Got around the space issue by downloading all drivers/libraries to /mnt (/media/ephemeral0), the nodes' instance store volume ([60GB for g2.2xlarge](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html)), instead of / (only 10GB). After installing the necessary packages, I cleared the files downloaded to this directory.

**Comment by davidmarin** [comment]
Cool. Thanks for letting me know about this.
