### ISSUE TITLE
mrjob/mrjob/examples/mr_page_rank.py is a wrong example

### ISSUE THREAD

**Issue by shanghaiyangming** [Yelp/mrjob#1189]
This implementation of the reduce function does not have a valid maintained Idempotency should be wrong

**Comment by davidmarin** [comment]
Oh, you mean it doesn't properly implement the Page Rank algorithm? How should I fix it?

**Comment by shanghaiyangming** [comment]
Later on, I will invite my colleague posted the correct code

**Comment by davidmarin** [comment]
Probably not going to fix this without further guidance.
