### ISSUE TITLE
How can i open image from sequence file using MrJob?

### ISSUE THREAD

**Issue by shomy4** [Yelp/mrjob#1193]
Im trying to analyze images from sequence file using opencv.My code looks like this:

    from mrjob.job import MRJob
    import os
    import sys 
    import cv2
    import numpy as np

    class CountLavander(MRJob):
        HADOOP_INPUT_FORMAT = 'org.apache.hadoop.mapred.SequenceFileAsTextInputFormat'
        def mapper(self, key, value)
            imgbytes = np.fromstring(value,dtype='uint8')
            imarr = cv2.imdecode(imgbytes, cv2.IMREAD_COLOR)
            yield imarr,1

        def reducer(self, key, values):
            yield key, sum(values)

    if __name__ == '__main__':
        CountLavander.run()

As a result um getting:
**null 2731**
for some reason it won't load the image but it goes trough each one of them(there are 2731 images in sequence file)
Can you tell me what im doing wrong?

**Comment by davidmarin** [comment]
Sadly, MRJob does not yet support sequence files (only line-based files).

One workaround is to upload your images to S3, and then pass your job a text file with the s3:// URL for an image file on each line.
