### ISSUE TITLE
How do you read S3 files that are encrypted?

### ISSUE THREAD

**Issue by jerynmathew** [Yelp/mrjob#1211]
My use case has S3 files that are encrypted using an AES key. I know boto3 supports S3 get_objects() with encryption. 
Will MRJob support encrypted S3 files, or move to Boto3? Or is there a better workaround?

**Comment by davidmarin** [comment]
Considered switching to boto3 at some point (or botocore), but then boto added Python 3 support. At some point (maybe 0.6?), we'll have to switch just to be current, but it's too much to handle for the 0.5 release.

For the near future, your best bet is to patch boto to include server side encryption, using boto3 as a model, and submit a pull request to the boto project on GitHub. Looks like there's some support for encryption already (see http://boto.cloudhackers.com/en/latest/ref/s3.html).

-Dave

**Comment by davidmarin** [comment]
Planning to switch to boto3 soon-ish; see #1304.

**Comment by davidmarin** [comment]
mrjob 0.6.0+ is on boto3, enjoy
