### ISSUE TITLE
EMRJobRunner._set_up_ssh_tunnel spams stdout

### ISSUE THREAD

**Issue by dadkins** [Yelp/mrjob#1212]
https://github.com/Yelp/mrjob/blob/master/mrjob/emr.py#L965

There's a print statement in there when it fails to setup the ssh tunnel. These go to stdout where they get mixed with real output! I'm guessing that should be a log message of some kind.

**Comment by davidmarin** [comment]
Weird, thank you for catching that. Just pushed the fix to `master`..
