### ISSUE TITLE
Working with zip files

### ISSUE THREAD

**Issue by jruizaranguren** [Yelp/mrjob#1216]
Is it possible to work with files compressed in `zip` format? 

[Added to StackOverflow](http://stackoverflow.com/questions/35107322/mrjob-reading-from-zip-files), I'm not sure if it is just a question or an issue.

**Comment by davidmarin** [comment]
Zip files are an *archive* format (they contain multiple files), so you can use them, to, say, upload your source code and put it into a directory, but not, say, to compress your input files.

mrjob works well with .gz and .bz2 compressed files. Hadoop also supports LZO and snappy compression; if you need either of these formats, let me know so I can add a ticket to mrjob.
