### ISSUE TITLE
IOError: Invalid Data Stream when using bz2 in windows x64

### ISSUE THREAD

**Issue by jruizaranguren** [Yelp/mrjob#1218]
I'm trying to make work a simple counting words job with compressed files. 

When I use a `bz2` file as input I'm getting `IOError: Invalid Data Stream`.

I'm executing the job with default conf:

```
python myjob.py inputfile.bz2
```

Error detail:

```
D:\Anaconda\lib\site-packages\mrjob\util.pyc in read_input(path, stdin)
    410 
    411     # read from files
--> 412     for line in read_file(path):
    413         yield line
    414 

D:\Anaconda\lib\site-packages\mrjob\util.pyc in read_file(path, fileobj, yields_lines, cleanup)
    456                 lines = buffer_iterator_to_line_iterator(f)
    457 
--> 458         for line in lines:
    459             yield line
    460     finally:

D:\Anaconda\lib\site-packages\mrjob\util.pyc in buffer_iterator_to_line_iterator(iterator)
     72     buf = ''
     73     search_offset = 0
---> 74     for chunk in iterator:
     75         buf += chunk
     76 

D:\Anaconda\lib\site-packages\mrjob\util.pyc in _bunzip2_stream(fileobj, bufsize)
    490             return
    491 
--> 492         part = d.decompress(chunk)
    493         if part:
    494             yield part

IOError: invalid data stream
```

I have compressed the file both in a Windows and Linux machine (in case it was a matter of the compression). I'm using mrjob 0.4.6 in a x64 Windows machine with Python 2.7.10.

The file can be opened with 7-zip with no problems.

**Comment by davidmarin** [comment]
Pretty sure this is because mrjob 0.4.6 opens the file in text mode, which runs into line-ending issues on Windows.

This has been fixed in the `master` branch on GitHub for some time and will soon be released as mrjob 0.5.0. Try it out; `master` has a lot of tests and is generally pretty stable.
