### ISSUE TITLE
failed to find counters in rotated syslog

### ISSUE THREAD

**Issue by dadkins** [Yelp/mrjob#1232]
I had a recent job fail to find counters in syslog when syslog got rotated mid-job:

$ aws s3 ls s3://mrjob-394dc542f5df5612/tmp/logs/j-1GIXXKEE3MJ2H/steps/s-2BQ5U0ZHTR16N/
2016-02-26 16:25:46       1439 controller.gz
2016-02-26 16:25:46         49 stderr.gz
2016-02-26 15:40:46        157 stdout.gz
2016-02-26 16:00:46       1733 syslog.2016-02-26-23.gz
2016-02-26 16:25:46       1323 syslog.gz

And from the console:
Attempting to fetch counters from logs...
Looking for step log in s3://mrjob-394dc542f5df5612/tmp/logs/j-1GIXXKEE3MJ2H/steps/s-2BQ5U0ZHTR16N...
  Parsing step log: s3://mrjob-394dc542f5df5612/tmp/logs/j-1GIXXKEE3MJ2H/steps/s-2BQ5U0ZHTR16N/syslog.2016-02-26-23.gz
No counters found

**Comment by davidmarin** [comment]
Huh! Looks like our regex is too broad; we should just be reading `syslog.gz`.

**Comment by davidmarin** [comment]
Oh, right, so we want to start by reading ``syslog.YYYY-MM-DD` in order by date, and then finish off with plain old `syslog`.

**Comment by davidmarin** [comment]
This is now totally easy to update the code and write tests for!

**Comment by davidmarin** [comment]
I'm guessing that, in theory, a multi-line log4j record (e.g. a stack trace) could be broken between two files, though that's probably incredibly rare in practice.

**Comment by davidmarin** [comment]
Just pushed the fix to `master`. Please try it out!

**Comment by dadkins** [comment]
Thanks! I just ran a multi-hour job and it picked up the counters from the logs, no problem.

**Comment by davidmarin** [comment]
Great!
