### ISSUE TITLE
generic options for EMR and Dataproc

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1247]
Now that we're going to have a [Dataproc](https://cloud.google.com/dataproc/) runner (see #1243), we should use the same option names in the EMR and Dataproc runners wherever this makes sense.

On the Dataproc runner, we should use these option names below ASAP (instead of the current `gce`/`gcp` names). On EMR, we should first introduce these as aliases for the AWS-specfic options in the EMR runner, and then, eventually, deprecate those options, removing them in v0.6.0.

Options having to do with credentials or API endpoints are probably best left with names specific to the service (e.g. `s3_endpoint`, not `cloud_fs_endpoint` or some such), as is hacky stuff like `additional_emr_info` and `emr_api_params`.

Here are the generic option names to use (followed by their current equivalents in the EMR and dataproc runners, if any)

 - `bootstrap` (not e.g. "initialization" in the Dataproc runner)
 - `bootstrap_actions`
 - `check_cluster_every` (check_api_status_every, check_emr_status_every)
 - `cloud_fs_sync_secs` (gcs_sync_wait_time, s3_sync_wait_time)
 - `cloud_log_dir` (s3_log_uri)
 - `cloud_tmp_dir` (gcs_tmp_dir, s3_tmp_dir)
 - `cloud_upload_part_size` (s3_upload_part_size)
 - `cluster_id` (gcp_cluster)
 - `core_instance_bid_price` (ec2_core_instance_bid_price)
 - `core_instance_type` (ec2_core_instance_type, ec2_slave_instance_type, gce_machine_type)
 - `image_version` (ami_version)
 - `instance_type` (ec2_instance_type, gce_machine_type)
 - `master_instance_bid_price` (ec2_master_instance_bid_price)
 - `master_instance_type` (ec2_master_instance_type)
 - `num_core_instances` (num_ec2_core_instances)
 - `num_task_instances` (num_ec2_task_instances)
 - `region` (aws_region, gcp_region)
 - `tags` (emr_tags)
 - `task_instance_bid_price` (ec2_task_instance_bid_price)
 - `task_instance_type` (ec2_task_instance_type)
 - `zone` (aws_availability_zone, gcp_zone)

The `*_bid_price` options don't really make sense on Dataproc (where instances are either preemptible or not, but there's no bidding); maybe want to call these options `preemptible_*_instances` once we implement this?

`emr_action_on_failure` could probably be replaced by something more generic, but there isn't a Dataproc equivalent, so we'll punt on that for now.

**Comment by davidmarin** [comment]
It's tempting to want to merge the `hdfs_tmp_dir` option in the Hadoop runner with `cloud_tmp_dir` (maybe calling it `remote_tmp_dir`), but I think these are distinct concepts. Really, there's the local FS, the cloud FS (which is accessible to Hadoop and from the API), and HDFS (which is only accessible to Hadoop).

**Comment by davidmarin** [comment]
Not really sure where `release_label` fits into this. Honestly, release labels and machine image versions are basically of the same thing; EMR just decided they wanted to reboot the AMI version interface. Probably rolling both into `image_version` is the right move.

**Comment by mtai** [comment]
Made varname changes before seeing this issue, what are your thoughts on the following?

- cluster_id (same)
- cloud_region (vs region)
- cloud_zone (vs zone)
- cloud_image (vs image_version)
- cloud_api_cooldown_secs (vs check_cluster_every)
- vm_type (vs instance_type)
- vm_type_master (vs ...)
- vm_type_worker (vs ...core)
- vm_type_preemptible (vs ...task)
- num_worker (vs num_instances/num_core_instances)
- num_preemptible (vs num_task_instances)
- fs_sync_secs (vs wait_for_eventual_consistency)
- fs_tmpdir vs (cloud_tmp_dir)

**Comment by davidmarin** [comment]
A serious discussion about naming! Yassss!

My main goal was to find as much common ground between EMR and Dataproc as possible, to make the naming as unsurprising as possible to users of both.

In some cases, seeing that two different systems use the same terminology allows me to be less timid about naming (for example, Dataproc and EMR both call regions "regions" and zones "zones", so I'm comfortable leaving off a qualifier like `aws_`).

Re: options about instance number and type, just take a look at the [InstanceGroupConfig](https://cloud.google.com/dataproc/reference/rest/v1/projects.regions.clusters#InstanceGroupConfig) for Dataproc. Except for `machineTypeUri`, "instance" is used throughout, and "vm" is used nowhere. `image_version`, too, comes straight out of Dataproc's [SoftwareConfig](https://cloud.google.com/dataproc/reference/rest/v1/projects.regions.clusters#SoftwareConfig).

task/core and preemptible/non-preemptible are distinct concepts. It's definitely possible for core nodes to be preemptible (just not a super idea).

If I could figure out how, I'd rather not use the term "cloud" at all; it's literally an amorphous term. The problem I was trying to solve with `cloud_tmp_dir` was distinguishing it from HDFS (which often can't be accessed at all without SSHing into the master node). I think "fs" is even more unclear than "cloud," but I'd certainly be open to other suggestions.

What's `api_cooldown_secs` based on? I don't love it, but I'm not wedded to `check_cluster_every` either.

**Comment by davidmarin** [comment]
Huh, just realized that there's a `REMOTE_TMP` cleanup option. Only EMR does this, so maybe I should seize the moment and rename it to `CLOUD_TMP`?

**Comment by davidmarin** [comment]
Amazon [describes S3](https://aws.amazon.com/s3/) as "cloud storage", and Google's cloud storage is literally named "Google Cloud Storage", so "cloud" is probably the right name for this.

**Comment by davidmarin** [comment]
I'd be fine with `num_instances` never existing as an option (and deprecating `num_ec2_instances`), since it's really just `num_core_instances` plus one.

**Comment by davidmarin** [comment]
Would like to get to this sooner rather than later, because it's easy to use the switches for the wrong runner and then, frustratingly, get no effect.

**Comment by davidmarin** [comment]
Probably better to keep `num_instances`; it allows people to think less when they're scaling up their first job.

**Comment by davidmarin** [comment]
This change is easy to do but represents a fair amount of nuisance for existing users, so should be released alongside with something useful.

**Comment by davidmarin** [comment]
Need to remember to refresh docstrings in `mrjob.tools.emr` when done.

**Comment by davidmarin** [comment]
Added `cloud_upload_part_size`, since Google Cloud Storage supports chunked uploads as well, and we're currently using a really small chunk size. See #1404

**Comment by davidmarin** [comment]
Nah, let's phase out `num_ec2_instances` and "slave" instances (same as "core").

**Comment by davidmarin** [comment]
`hadoop_streaming_jar_on_emr` shouldn't be genericized; it should be phased out; see #1405.
