### ISSUE TITLE
0.5.0: broken EMR secondary sort?

### ISSUE THREAD

**Issue by andrey-cliqz** [Yelp/mrjob#1294]
If I specify `SORT_VALUES=True` on the `MRJob` subclass, it would add the following arguments to EMR step:
```
-D mapred.text.key.partitioner.options=-k1,1 
-partitioner org.apache.hadoop.mapred.lib.KeyFieldBasedPartitioner 
```
In version 0.5.0 it doesn't add `-partitioner` argument but adds only `-D mapred.text.key.partitioner.options=-k1,1`, which can be easily tested by the following code (or any other code that uses `SORT_VALUES`):
```
from mrjob.job import MRJob
from mrjob.protocol import RawProtocol, JSONValueProtocol
import uuid

class SecondarySortJob(MRJob):
    INPUT_PROTOCOL = RawProtocol
    OUTPUT_PROTOCOL = JSONValueProtocol
    SORT_VALUES = True

    def mapper(self, _, line):
        yield str(uuid.uuid4()), line

    def reducer(self, k, docs):
        for d in docs:
            yield None, d

if __name__ == '__main__':
    SecondarySortJob.run()
```

I haven't fully debugged it so I may miss something, but it seems like the new behaviour was introduced by [this change](https://github.com/Yelp/mrjob/commit/98ef509208ada4b96a964ff4eef34adfda74a272). Here, `self._get_kwargs_from_opt_group(self.hadoop_emr_opt_group)` returns a dictionary with `'partitioner': None`, which overrides the value from the `job_runner_kwargs()` call.

I also found one workaround for this, which is to specify `--partitioner 'org.apache.hadoop.mapred.lib.KeyFieldBasedPartitioner'` CLI option.

**Comment by davidmarin** [comment]
Thanks!

**Comment by davidmarin** [comment]
Oh, I see the problem. Partitioners are supported by every runner (though ignored on the local runners), but we only add the `--partitioner` option for the Hadoop and EMR runners. Should just allow `--partitioner` for all runners.

**Comment by davidmarin** [comment]
Thank you for catching this! Please try it and let me know if it works for you now.

**Comment by andrey-cliqz** [comment]
Thanks, I'll post here after I try the fixed version.

**Comment by andrey-cliqz** [comment]
I've just tried running a job with the latest version (0.5.2) and the sorting seems to works. Thanks for the fix!
