### ISSUE TITLE
EC2 subnet option

### ISSUE THREAD

**Issue by jitesh1337** [Yelp/mrjob#1323]
Hi all,
I am trying to pass in a SubnetID to an Amazon EMR cluster I am trying to start. Reading here (http://docs.aws.amazon.com/cli/latest/reference/emr/create-cluster.html) I understand that I have to pass it via --ec2_attributes. mrjob doesn't support passing in this parameter to create-cluster. Any pointers on how I could add this?

Jitesh

**Comment by davidmarin** [comment]
`--emr-api-param`, I guess? :) I'll try to add support for this in the next mrjob version.

**Comment by jitesh1337** [comment]
^^ That worked. Thanks! 

I had some trouble passing in "Configurations" parameters too (emr-4.2.0). Found #1276 though and will gladly wait for it. I did get a bunch of it working using hadoop_extra_args, so no worries there.

**Comment by davidmarin** [comment]
Looks like I should just add `--ec2-subnet-id`. `Ec2KeyName` is already covered by `--ec2-key-pair`.

**Comment by davidmarin** [comment]
Just for the record, the workaround is:

```
emr_api_params:
  Instances.Ec2SubnetId: subnet-xxxxxxxx
```

Yelp's been doing this for a while!

**Comment by davidmarin** [comment]
Google Dataproc [has a subnet option](https://cloud.google.com/sdk/gcloud/reference/beta/dataproc/clusters/create) that works somewhat similarly (see also the [subnetUri API parameter]((https://cloud.google.com/dataproc/reference/rest/v1/projects.regions.clusters#GceClusterConfig)). In the interest of not having to harmonize these options later (see #1247), going to call this option `subnet`.
