### ISSUE TITLE
JSONDecodeError while running job on EMR

### ISSUE THREAD

**Issue by mpenkov** [Yelp/mrjob#1324]
I'm attempting to run a job on EMR. I'm seeing my job fail due to raised JSONDecodeError in underlying code.

There are several places where this exception is raised. For example, it happens while the combiner/reducer are reading their input:

```
ERROR:root:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mr_stage_a.py", line 177, in combiner
    for (score, output_dict) in sorted(tuples):
  File "/usr/lib/python2.7/site-packages/mrjob/job.py", line 593, in <genexpr>
    values = (v for k, v in kv_pairs)
  File "/usr/lib/python2.7/site-packages/mrjob/job.py", line 672, in read_lines
    key, value = read(line.rstrip(b'\r\n'))
  File "/usr/lib/python2.7/site-packages/mrjob/protocol.py", line 88, in read
    self._last_key_decoded = self._loads(raw_key)
  File "/usr/lib/python2.7/site-packages/mrjob/protocol.py", line 158, in _loads
    return simplejson.loads(value)
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

In this case, mr_stage_a.py is my code, so I can catch the exception with something like:

```
    def combiner(self, domain, tuples):
        try:
            for (score, output_dict) in sorted(tuples):
                # do stuff here
        except ValueError as e:
            #
            # https://github.com/Yelp/mrjob/issues/544
            #
            if e.message.startswith("Expecting value: "):
                logging.error("combiner: unable to decode JSON")
                logging.exception(e)
            else:
                raise
```

However, the same exception is also raised by internal mrjob code:

```
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "mr_stage_a.py", line 295, in <module>
    MrStageA.run()
  File "/usr/lib/python2.7/site-packages/mrjob/job.py", line 430, in run
    mr_job.execute()
  File "/usr/lib/python2.7/site-packages/mrjob/job.py", line 442, in execute
    self.run_combiner(self.options.step_num)
  File "/usr/lib/python2.7/site-packages/mrjob/job.py", line 592, in run_combiner
    key=lambda k_v1: k_v1[0]):
  File "/usr/lib/python2.7/site-packages/mrjob/job.py", line 672, in read_lines
    key, value = read(line.rstrip(b'\r\n'))
  File "/usr/lib/python2.7/site-packages/mrjob/protocol.py", line 88, in read
    self._last_key_decoded = self._loads(raw_key)
  File "/usr/lib/python2.7/site-packages/mrjob/protocol.py", line 158, in _loads
    return simplejson.loads(value)
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 5 (char 4)
```

In this case, I can't do anything to catch the error, so it crashes the entire job.

What's going on and how can I avoid these errors?

**Comment by davidmarin** [comment]
mrjob is using JSONProtocol to decode the data before it gets passed to combiner(), reducer() etc., so you can’t catch the exception there. You can write a protocol that’s more appropriate for your data, or if it’s just a matter of a few bad lines, you can use —no-strict-protocols for now (though it’s deprecated and going away).

See:

    https://pythonhosted.org/mrjob/protocols.html

for more details.

Does your job not have a mapper? Usually the combiner/reducer just get the output of the mapper (which is properly JSON-encoded by default), so I’m confused as to how they’re getting non-JSON input.

-Dave

**Comment by mpenkov** [comment]
I will try "--no-strict-protocols" as a temporary work-around and let you know how that goes. In the meanwhile, I'd like to get to the bottom of this (I'm sure you do, too ;)), so...

My job has a mapper. It does this:

```
class MrStageA(CCJob):

    def process_record(self, record):
        if record['Content-Type'] == 'application/http; msgtype=response':
            uri = record["WARC-Target-URI"]
            parsed = urlparse.urlparse(uri)
            domain = parsed.netloc
            is_homepage = parsed.path in ["", "/"]
            if is_homepage:
                payload = record.payload.read()
                #
                # The HTTP response is defined by a specification: first
                # part is headers (metadata) and then following two CRLFs
                # (newlines) has the data for the response
                #
                headers, body = payload.split('\r\n\r\n', 1)
                if 'Content-Type: text/html' in headers:
                    try:
                        uri = to_utf8(uri)
                        output_dict = split_html(uri, body)
                        key, value = domain, (score, output_dict)
                        yield key, value
                    except (UnicodeEncodeError, UnicodeDecodeError):
                        logger.error("Unicode encode/decode error: %s", uri)

        self.increment_counter('commoncrawl', 'processed_records', 1)
```

where CCJob is from [here](https://github.com/Smerity/cc-mrjob/blob/master/mrcc.py). `split_html` returns a dict that contains the title (string), headings (list of string), and body text (string) from the HTML. 

I originally thought that stray newlines/tabs in `key` or `value` were the problem, but this doesn't seem to affect simplejson since it escapes them during encoding:

```
In [60]: simplejson.dumps({"foo": "bar\tbaz"})
Out[60]: '{"foo": "bar\\tbaz"}'
In [61]: simplejson.dumps({"foo": "bar\tbaz"}).split("\t")
Out[61]: ['{"foo": "bar\\tbaz"}']
```

What else could the problem be? Are there any restrictions on how long the value should be?

**Comment by davidmarin** [comment]
Oh, that's weird. Yeah, if you have a mapper, it should just be emitting JSONs. Stray newlines or tabs were my first idea too.

Can you try running your job with just the mapper (remove or disable the combiner and reducer), and then scan the output for suspicious lines (either write a custom script or a MRJob with a trivial mapper that uses `INPUT_PROTOCOL = JSONProtocol`)?

**Comment by davidmarin** [comment]
Also, of course if you can give me any way to duplicate it, that'll make it a lot easier to catch this bug. :)

**Comment by mpenkov** [comment]
OK, I've packaged together a job and shared it as a [gist](https://gist.github.com/mpenkov/401f62731709cd05ca3de860d8ee7d17).

To run:

    python mr_stage_a.py test-1.warc -r emr --conf-path mrjob.conf --output-dir s3://your-bucket/test-1.out --no-output

Grab the results:

    aws s3 sync s3://your-bucket/test-1.out test-1.out

Check:

    python check.py < test-1.out/part-00000

You should get several badnesses reported, on examination, it seems that they're all log statements (from Python's builtin logging module) that have *somehow* made their way into the output. 

Does that seem right to you?

I think the problem is this line in my script:

    logger.addHandler(logging.StreamHandler(sys.stdout))

I've changed it to:

    logger.addHandler(logging.StreamHandler(sys.stderr))

and retried. The badnesses from the output are gone.

Should streaming logging to stdout cause this kind of problem?

**Comment by davidmarin** [comment]
Ohhhh...

Yes, Hadoop Streaming considers anything on `stdout` to be the output of your job. It doesn't have a way of distinguishing your logging messages from your job's data (and then the reducers have to try to parse those messages).

`stderr` is definitely the place to log to.

**Comment by mpenkov** [comment]
Ouch. Thanks for the tip, and sorry for the hassle.
