### ISSUE TITLE
[Feature Request] Configure inputs for steps separately

### ISSUE THREAD

**Issue by jitesh1337** [Yelp/mrjob#1333]
I have a two-step job. First step being s3-dist-cp which copies over data from S3 to HDFS using EMR. The output of this step does NOT come via stdout. The step following this which processes the data, thus, needs a way to configure input path separately. I didn't find a way to do this currently. mrjob by default uses output directory of the previous job as input of the next.

Is there interest in enabling such a use-case? I might put up a pull-request if you guys are interested.

**Comment by davidmarin** [comment]
It sounds like what you're trying to do is more like setup than an actual job step. Let's handle this with #1336.

I see what you're saying; if you had more control over the flow of data, you could solve this with a `JarStep` using `script-runner.jar`.

mrjob isn't really designed to handle anything more than a linear pipeline of steps gracefully; if you need more than that, break your pipeline into multiple steps and [run them programmatically](https://pythonhosted.org/mrjob/guides/runners.html#running-your-job-programmatically).

That's actually the current workaround for this case; your first job has a single `JarStep` which runs `s3-dist-cp` using `script-runner.jar`, and your second job runs normally (using the same cluster ID as the first job), using an HDFS path as input. It's... not great, and I'll see if I can make progress on #1336.
