### ISSUE TITLE
Testing without nosetests raises errors

### ISSUE THREAD

**Issue by etiennebatise** [Yelp/mrjob#1335]
Hi all,

I have been working on a project and wrote some tests with the `unittest` package and it has been working fine all along. I have recently decided to use `nose` to write my tests but I've ran into a weird issue.

  - Here is what I did **before**:
    ```
    $ python -m unittest -v tests/tests_match_people_job.py
    ```
    It still works and run without errors.

  - Here is what I want to do **now**:
    ```
    $ nosetests
   ```

The last one returns this:
```
======================================================================
ERROR: Test the reducer_by_id function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/etiennebatise/Documents/scraping/mapreduce/tests/test_match_people_job.py", line 93, in test_reducer_by_id
    job = MatchPeopleJob()
  File "/Users/etiennebatise/Documents/scraping/mapreduce/testenv/lib/python3.5/site-packages/mrjob/job.py", line 100, in __init__
    super(MRJob, self).__init__(self.mr_job_script(), args)
  File "/Users/etiennebatise/Documents/scraping/mapreduce/testenv/lib/python3.5/site-packages/mrjob/launch.py", line 130, in __init__
    self.stdout = sys.stdout.buffer
AttributeError: '_io.StringIO' object has no attribute 'buffer'

----------------------------------------------------------------------
```

What I understand is that I can't create a job object without giving it something as input. But as it is working fine without nosetests, I guess the problem does not come from mrjob. Still, an explanation about this error would maybe help me fix it.

**Comment by davidmarin** [comment]
Looks like you want tests.py2.mock_stdout_or_stderr().

If it’s not in your path (tests don’t get installed with mrjob), just copy it out of the source:

    https://github.com/Yelp/mrjob/blob/master/tests/py2.py

-Dave

**Comment by etiennebatise** [comment]
Thank you, worked perfectly!

Fix 
```
from py2 import *

...

sys.stdout = mock_stdout_or_sterr()
```

**Comment by etiennebatise** [comment]
Alternatively, one could also do `nosetests -s`
