### ISSUE TITLE
add /var/log/hadoop-yarn to list of standard log dirs

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1339]
This seems like a pretty common default for YARN log dirs, and isn't necessarily reflected as an environment variable. (Of course we don't do this on Hadoop 1.)

Thanks @rschroll, for showing me this!

**Comment by davidmarin** [comment]
`/var/log/hadoop` also looks to be pretty standard.

**Comment by rschroll** [comment]
As a bit of a wrinkle to this, these directories have default 710 permissions and are owned by the yarn user.  (At least in our setup.)  Even when mrjob looks in the right place, it's running as the real user, and can't access the logs.  This used to be hardcoded into hadoop, but was made configurable back in February: https://github.com/apache/hadoop/commit/d7fdec1e6b465395d2faca6e404e329d20f6c3d8.  I don't this has made it into any release yet.  It may not be worth working on this issue until the permissions are configurable.
