### ISSUE TITLE
Job throws BrokenPipe Error

### ISSUE THREAD

**Issue by etiennebatise** [Yelp/mrjob#1392]
Hi all, 

I am having an issue running a job on EMR. I have 82 snappy compressed files (~120MB) as input on s3, the job is running on an emr cluster sized like this:
- 1 **master** nodes m3.xlarge
- 3 **core** nodes m3.xlarge with a lot of EBS storage
- 10 **task** instance nodes c4.4xlarge 

It gets to 10% and then fails with a `java.io.IOException: Broken pipe` in the terminal.

When digging into the logs, I've found in some containers some more explicit output:

```
+ python3 match_people_job.py --step-num=0 --mapper
Traceback (most recent call last):
  File "match_people_job.py", line 43, in <module>
    MatchPeopleJob.run()
  File "/usr/local/lib/python3.4/site-packages/mrjob/job.py", line 430, in run
    mr_job.execute()
  File "/usr/local/lib/python3.4/site-packages/mrjob/job.py", line 439, in execute
    self.run_mapper(self.options.step_num)
  File "/usr/local/lib/python3.4/site-packages/mrjob/job.py", line 505, in run_mapper
    write_line(out_key, out_value)
  File "/usr/local/lib/python3.4/site-packages/mrjob/job.py", line 685, in write_line
    self.stdout.write(write(key, value))
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

In the global logs of Hadoop, I've found that between 2 java stack traces:  

```
Container killed by the ApplicationMaster.
Container killed on request. Exit code is 143
Container exited with a non-zero exit code 143
```

Some people suggested trying to change the number / allocated memory of map & reduce tasks in the jobconf field but it didn't have any effect. I also tried pumping up more instances in the cluster but it didn't help either. Actually, ganglia was showing that the cluster was not overloaded at all. 

As I understand it, something failed and the ApplicationMaster just killed the containers, but I can't see any logs as for why it failed. This happens when stout.write is called so I supposed it was a storage problem but the code nodes have already plenty of space available.

I've already run my job on 10% of the input and it worked perfectly. Any idea on how to solve this? 

_python3, mrjob 5.2.0_

**Comment by timseries** [comment]
Have also run into this issue...is there any resolution on this?

**Comment by timseries** [comment]
I'm also finding my job succeeds on a smaller input size (50%), but fails on the full input size. Also tried increasing hadoop jobconf memory allocation parameters, with no success.
