### ISSUE TITLE
Issue parsing .gz files

### ISSUE THREAD

**Issue by jolson7168** [Yelp/mrjob#1409]
I have two .gz files: 1.gz and 2.gz

mrjob operating on both of them yields the expected results.

If I concatenate them into a single file in compliance with [RFC 1952 for gzip](http://www.gzip.org/zlib/rfc-gzip.html#file-format) by doing the following:

``
$ cat 1.gz 2.gz > 3.gz
``

and then use 3.gz as the input to mrjob, only the contents of pre-concatenated 1.gz will be aggregated by mrjob. 

Observations:

- If 3.gz is sufficiently large (low hundreds of MBs), mrjob will hang when processing it. If 3.gz is small (low hundres of KBs, mostly used for testing and debugging), mrjob will complete, but will only operate and report on the the contents of the pre-concatenated 1.gz file.

- 3.gz uncompresses to the uncompressed contents of 2.gz appended to the uncompressed contents of 1.gz as expected

- mrjob operates on the uncompressed 3.gz file as expected. 

- If you then re-gzip the uncompressed 3.gz back to 3.gz, mrjob will operate on that as expected. 

Somehow mashing the two compressed files together causes mrjob to only process the first of the concatenated files. If you concatenate N .gz files together, mrjob only processes the first one in the concatenation order.

**Comment by davidmarin** [comment]
Based on what I've been able to piece together from StackOverflow, you're right that you can concatenate gzipped streams, but the `.gz` file header makes things complicated. `gunzip` is smart enough to know to ignore file headers in the middle of the stream, but Python's `gzip` library and Hadoop are likely not.

Just curious, why are you concatenating your `.gz` files before passing them to Hadoop? Too many input files? Trying to control which files go to the same mapper?
