### ISSUE TITLE
Documentation incorrect for --hadoop-extra-arg

### ISSUE THREAD

**Issue by srwilson** [Yelp/mrjob#1412]
https://pythonhosted.org/mrjob/guides/configs-hadoopy-runners.html#options-available-to-hadoop-and-emr-runners

This guide shows the argument as `--hadoop-extra-arg` but in options.py it's `--hadoop-arg`

```
 opt_group.add_option(
            '--hadoop-arg', dest='hadoop_extra_args', default=[],
            action='append', help='Argument of any type to pass to hadoop '
            'streaming. You can use --hadoop-arg multiple times.'),
```

**Comment by davidmarin** [comment]
Thanks for catching this. The fix is now live on readthedocs: http://mrjob.readthedocs.io/en/latest/guides/configs-hadoopy-runners.html
