### ISSUE TITLE
hand-test Spark 2 support

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1416]
AMI 5.0.0 runs Spark 2.0.0; see https://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-spark.html

Once we have a working solution in place, should double-check that our examples and log interpretation still work correctly.

**Comment by niloygupta** [comment]
This would be a great to have!

**Comment by davidmarin** [comment]
Ran the `SparkPi` example successfully on Spark 2.

**Comment by davidmarin** [comment]
`mrjob.examples.mr_spark_wordcount` seems to work fine on Python 2 with image version 5.0.0 (which runs Spark 2).

There seem to be some issues with bootstrapping mrjob in Python 3 on that AMI; trying to figure that out now.

**Comment by davidmarin** [comment]
Spark 2 works fine with Python 3. The problem was #1503.
