### ISSUE TITLE
v0.5.5: Does not translate from dataproc image version to dataproc hadoop version

### ISSUE THREAD

**Issue by ojalvotron** [Yelp/mrjob#1428]
In dataproc.py._store_cluster_info the value returned in cluster['config']['softwareConfig']['imageVersion']) is not present in _DATAPROC_IMAGE_TO_HADOOP_VERSION.

cluster['config']['softwareConfig']['imageVersion']) returns '1.0.11' instead of the expected '1.0'

MacOSX 10.11.6 - updated to the latest version of gcloud tools

**Comment by davidmarin** [comment]
Thanks for noticing this!

**Comment by davidmarin** [comment]
Hmm, I don't *think* the dataproc API will tell you which Hadoop version it's running, but I'll double-check that. At the very least, it shouldn't crash; if we don't have information about a new image version, we'll assume the last Hadoop version that we know about.

**Comment by ojalvotron** [comment]
Well, dataproc returns 1.0.11 (instead of 1.0) as image version and the translate table in dataproc.py doesn't have this value (_DATAPROC_IMAGE_TO_HADOOP_VERSION)

**Comment by zbagz** [comment]
I also noticed the same error. This is how I fixed in my fork:

https://github.com/zbagz/mrjob/commit/0657b25601cc2c3e4eb3f1a1057b2791dd56054d

**Comment by davidmarin** [comment]
Shoot, I'm trying to duplicate this bug, and having some trouble getting Dataproc to provision clusters. Going to try again tomorrow.

I think the correct fix is to use `mrjob.compat.map_version()` against `_DATAPROC_IMAGE_TO_HADOOP_VERSION` rather than a simple dictionary lookup. That way, the worst that will happen is that we'll report the hadoop version for an older dataproc image. Dataproc is all Hadoop 2 anyway; the particular version of Hadoop isn't going to make much difference to mrjob.

If it's possible to get Dataproc to report the Hadoop version, that would be ideal, but I don't see anything about that in the docs. Going to doublecheck by seeing what the API returns.

**Comment by davidmarin** [comment]
Ah, I see, the current code tries to default dataproc's image version to a known version x.y, but the API returns x.y.z. So it doesn't *look* like brittle code, but its assumption about API behavior is wrong.

I'm going to go with `map_version()`, but @zbagz's patch is a legit approach too.

**Comment by davidmarin** [comment]
(By the way, apparently something was wrong with my Google Cloud project that was making it impossible to provision clusters. Creating a new project fixed it, and now I'm able to hand-test.)

**Comment by davidmarin** [comment]
Guessing the correct way to get the Hadoop version is from `cluster['config']['masterConfig']['imageUri']`. Trying to figure out how to fetch that.

**Comment by davidmarin** [comment]
Relevant docs here: https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.clusters#InstanceGroupConfig

**Comment by davidmarin** [comment]
Never mind, `imageUri` doesn't contain info about Hadoop version either. When I fetched `https://www.googleapis.com/compute/v1/projects/cloud-dataproc/global/images/dataproc-1-0-20160830-191542?alt=json` from the API, here's what I got:

```
{u'archiveSizeBytes': u'2058489724',
 u'creationTimestamp': u'2016-08-30T19:51:17.306-07:00',
 u'description': u'',
 u'diskSizeGb': u'10',
 u'id': u'8605770490913224906',
 u'kind': u'compute#image',
 u'licenses': [u'https://www.googleapis.com/compute/v1/projects/cloud-dataproc/global/licenses/dataproc'],
 u'name': u'dataproc-1-0-20160830-191542',
 u'rawDisk': {u'containerType': u'TAR', u'source': u''},
 u'selfLink': u'https://www.googleapis.com/compute/v1/projects/cloud-dataproc/global/images/dataproc-1-0-20160830-191542',
 u'sourceType': u'RAW',
 u'status': u'READY'}
```
