### ISSUE TITLE
Control reading data into mapper

### ISSUE THREAD

**Issue by rylanchiu** [Yelp/mrjob#1448]
Given a document of  `user-movie-rating`, I wanna ensure all the data of the each user go to the same mapper. How can I implement it with mrjob? Thanks in advance!

**Comment by davidmarin** [comment]
The usual approach is to have the mapper emit `(user_id, data)` and then process it in a reducer (all data with the same key, that is, `user_id`, go to the same reducer).

Is there a reason this wouldn't work for you?
