### ISSUE TITLE
Custom configuration for each instance group

### ISSUE THREAD

**Issue by bchess** [Yelp/mrjob#1451]
mrjob supports the `emr_configurations` settings for EMR 4.x and 5.x, but only for cluster-wide settings. [RunJobFlow](http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_RunJobFlow.html) also supports custom configuration per instance group.

It'd be nice to add support for this in mrjob. In some of our CPU constrained jobs, we want to set yarn.nodemanager.resource.cpu-vcores accurately for each instance type. And since different instance groups can have different instance types, we'd want to be able to have different settings for them.

**Comment by davidmarin** [comment]
Good point. Probably should just expose [InstanceGroupConfig](http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_InstanceGroupConfig.html) directly to avoid an explosion of options (e.g. `master_instance_group_config`, `core_instance_group_config` etc.).

This will be easier to do once we move to boto3 (see #1304).

**Comment by davidmarin** [comment]
This is fixed in v0.6.0 with the `instance_groups` option.
