### ISSUE TITLE
Bug in is_uri()

### ISSUE THREAD

**Issue by jerynmathew** [Yelp/mrjob#1455]
Hi Guys,

Found a bug when trying to use FileSystem().join().

A simple test for _mrjob.parse.is_uri('2016-10-11T06:29:17')_ returns **True**. As in, mrjob.parse.urlparse() is actually parsing the above datetime string and returning a _netloc_ object.

As a result, all dependencies are affected. I discovered it accidentally when trying to append a DateTime string to a S3 URl using The S3FileSystem().join() .

**Comment by davidmarin** [comment]
Thanks!

**Comment by davidmarin** [comment]
I'd say this is a bug in `is_uri()`. `mrjob.parse.urlparse()` is just a very thin wrapper around the real `urlparse()` that fixes a Python 2.6 bug.
