### ISSUE TITLE
identifying failing input files

### ISSUE THREAD

**Issue by uttara-cmu** [Yelp/mrjob#1517]
When using MRjob to process a set of files of which some may be corrupt, it would be helpful to know which files cause the job to fail (on say, a Hadoop error).

For example, I have Twitter files sampled every 15-minutes for a bunch of years of which some of them are corrupt (I get a `java.io.IOException: invalid distance code` error). I tried skipping these files as mentioned [here]( http://devblog.factual.com/practical-hadoop-streaming-dealing-with-brittle-code), but it looks like this does not work for streaming. I don't care about missing some files as long as I know which ones are faulty. Right now, I keep running MRjob in small batches until the job fails and this is taking a long time to find out which files are problematic.

Based on the discussion in #361 with @davidmarin, I think it would be tremendously useful to have a way to identify these corrupt files.

**Comment by davidmarin** [comment]
Huh, I'm pretty sure mrjob will tell you which input file a mapper was reading when it failed.

Also, you could try running your job with `--jobconf mapreduce.map.failures.maxpercent=<p>`, which would tell Hadoop to allow the job to skip up to *p* percent of input files.
