### ISSUE TITLE
Does mrjob support getting info of files in HDFS?

### ISSUE THREAD

**Issue by raiden2012** [Yelp/mrjob#1553]
Looks like HadoopFilesystem has no such method to get information of files in HDFS. It miss a lot info given by 'hadoop fs -ls -R', like owner and creation time. Is there any other way to get these file info?

**Comment by davidmarin** [comment]
In mrjob 0.5.x, you can use `runner.fs.invoke_hadoop()` on `HadoopJobRunner`s to run arbitrary Hadoop commands and get the output.
