### ISSUE TITLE
Failed to import mrjob on EMR

### ISSUE THREAD

**Issue by mirth** [Yelp/mrjob#1566]
So i'm trying to run my mrjob but getting the error on the first line:

```
ImportError: No module named mrjob.job
```
I'm launching job as the following:

`python main.py --bootstrap-mrjob -v -r emr --emr-job-flow-id j-XXXXXXXXX ../data/data.txt`

I also tried to add the following line into my mrjobs.conf:

```
bootstrap:
- sudo pip install mrjob
```
It doesn't work. So how to fix it?

**Comment by davidmarin** [comment]
Looks like your problem is that mrjob isn't installed locally, or at least isn't in your `PYTHONPATH`.
