### ISSUE TITLE
Inconsistent results when combiner creates new keys

### ISSUE THREAD

**Issue by rschroll** [Yelp/mrjob#1578]
I don't know if this is a bug in MRJob, a bug in Hadoop, or completely expected behavior.  Please feel free to close this if it's not a MRJob problem.

Consider the following code:
```python
class MRCombinerProblem(MRJob):

    def mapper_init(self):
        for i in xrange(3):
            yield None, i

    def mapper(self, _, line):
        pass

    def combiner(self, _, values):
        for i in values:
            yield 'key1', i
            yield 'key2', i

    def reducer(self, key, values):
        yield "Key", (key, sum(1 for _ in values))
```

The important bit is the combiner, which creates new keys, instead of just reducing the values for the incoming keys and passing them on to a reducer.  (I'm generating values in the mapper_init for ease, but that is immaterial.)  If I run this with `-r hadoop`, I get
```
"Key"   ["key1",2] 
"Key"   ["key2",1] 
"Key"   ["key1",1] 
"Key"   ["key2",1] 
"Key"   ["key1",1] 
"Key"   ["key2",2] 
"Key"   ["key1",1] 
"Key"   ["key2",1] 
"Key"   ["key1",1] 
"Key"   ["key2",1] 
```
With `-r inline` or `-r local`, I get
```
"Key"   ["key1",6]
"Key"   ["key2",6]
```
In all cases, it's running two mappers and a single reducer.

My guess is that Hadoop is sorting the keys before sending them to the reducer, and assuming the keys coming out the reducer will still be sorted.  Usually this is safe, but here we're producing mixed-up keys.

Assuming this is the case, it's not clear to me where the problem lies.  Is Hadoop MapReduce supposed to be able to handle this?  Is MRJob supposed to pass things back in sorted order?  Or are combiners supposed to leave keys alone?  If you tell me that this is just plain invalid code, I'll believe you!

This is seen on MRJob 0.5.9 and Hadoop 2.5.0.

**Comment by rschroll** [comment]
To answer the obvious question: A student encountered this problem when trying to implement reservoir sampling in a combiner.  The obvious solution is to just do the sampling in the mapper.  And that works just fine.  But I was curious why it failed, and that lead me here.

**Comment by davidmarin** [comment]
Combiners are treated as an optional optimization by Hadoop, so it may just not be running your combiner. Technically, Hadoop has the right to run the same combiner multiple times too!

On April 26, 2017 3:26:27 PM PDT, Robert Schroll <notifications@github.com> wrote:
>To answer the obvious question: A student encountered this problem when
>trying to implement reservoir sampling in a combiner.  The obvious
>solution is to just do the sampling in the mapper.  And that works just
>fine.  But I was curious why it failed, and that lead me here.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Yelp/mrjob/issues/1578#issuecomment-297559277

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rschroll** [comment]
We know it's running the combiner (since that's what gives the "key1" and "key2" values, and we know it's running the combiner only once (since the combiner doubles the number of items, and we're ending up with 12 total).  But if Hadoop reserves the right to run a combiner multiple times, it must be idempotent, which this combiner obviously isn't!

I'll close the bug.  Thanks for the insight!
