### ISSUE TITLE
support MultipleInputs?

### ISSUE THREAD

**Issue by xiaocao** [Yelp/mrjob#1593]
does it support MultipleInputs in mrjob? like this In java: 

`MultipleInputs.addInputPath(conf, path, inputFormatClass, mapperClass)`

to add multiple inputs with a different mapper for each.

I found something about MultipleInputs implemention in streaming:
https://github.com/hyonaldo/hadoop-multiple-streaming

**Comment by davidmarin** [comment]
Not in normal map/reduce mode, though there's doubtless something like this for Spark.

However, you can use `jobconf_from_env()` to figure out which input file a mapper is reading, and then process the data accordingly. Something like this:

```python
from mrjob.compat import jobconf_from_env()
from mrjob.job import MRJob

class MRYourJob(MRJob):

    def mapper(self, key, value):
        input_path = jobconf_from_env('mapreduce.map.input.file')

        if input_path ... :
            ...
```

**Comment by xiaocao** [comment]
thank you, davidmarin
