### ISSUE TITLE
Errors occur when using setup commands

### ISSUE THREAD

**Issue by danielchamberlain** [Yelp/mrjob#1607]
When I run the job using the following command, my job completes successfully:
`python cc_mrjob/mr_find_forums.py -r emr warc_lists/debug_CC-MAIN-2017-13`

However, when I modify the command to include a setup option, it fails:
`python cc_mrjob/mr_find_forums.py -r emr warc_lists/debug_CC-MAIN-2017-13 --setup 'sudo pip install langid'`

This error is not because of pip, the following command fails as well:
`python cc_mrjob/mr_find_forums.py -r emr warc_lists/debug_CC-MAIN-2017-13 --setup 'export PYTHONPATH=$PYTHONPATH:cc_mrjob/#'`

The stderr for one of my containers is shown below. As best I can tell, each container has either this message or a subset of these lines, sometimes only showing the first line.
> /bin/sh: run_prestart: line 1: syntax error: unexpected end of file
> log4j:WARN No appenders could be found for logger (org.apache.hadoop.mapred.Task).
> log4j:WARN Please initialize the log4j system properly.
> log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by davidmarin** [comment]
Yes this is #1548; basically EMR messed up `sh -e` on AMI 5.2.0 and later, requiring a special workaround. Upgrading to the latest version of mrjob should fix this issue.
