### ISSUE TITLE
Advanced EMR usage --emr-cluster-id option not found

### ISSUE THREAD

**Issue by mlorenzana** [Yelp/mrjob#1616]
I am attempting to use the --emr-cluster-id option found in the documentation, but cannot get this option to work, both from the command line and from the config file. In both cases, the output states that the option is not found.

https://pythonhosted.org/mrjob/guides/emr-advanced.html

A quick look through the code base, I cannot find this option, but can find other Advanced EMR options such as pool-clusters.

**Comment by davidmarin** [comment]
Shoot, it’s been renamed to simply --cluster-id. I’ll update the documentation.

-Dave

**Comment by budowski** [comment]
The docs still need updating - got me very confused as well until I found this GH issue...

**Comment by davidmarin** [comment]
Updated at https://mrjob.readthedocs.io/en/latest/guides/emr-advanced.html

(no one can update pythonhosted.org anymore)
