### ISSUE TITLE
Getting the information on steps associated with an EMRJobRunner?

### ISSUE THREAD

**Issue by okomestudio** [Yelp/mrjob#1625]
I'm using `mrjob` programatically and wish to add behaviors that depends on the status of steps associated with a particular (multi-step) EMR job. For example, I'd like to detect how a job finished (the status of last-run step and cancelled "pending" tasks queued after that last-run step).

It does not appear that there is publically accessible interface for obtaining step IDs for a job aside from `EMRJobRunner._job_step_ids()` which is meant to be a private helper.

Is there currently an idiomatic way to get a list of step IDs? If not what about adding a property/method that allows us to fetch this information? (Or simply making `_job_step_ids()` "public", I suppose...)

**Comment by davidmarin** [comment]
Making it public would probably be fine. Thanks for sharing your use case.
