### ISSUE TITLE
Is it possible to ignore file names that start with underscore in local mode?

### ISSUE THREAD

**Issue by yurii-cliqz** [Yelp/mrjob#1627]
I have job that generates data and a few files that look like this: `_FILE`. I use data from this folder as the input to the next job. When I run in the cluster these files are ignore, but in local mode job reads it. Is it possible to ignore these files in local mode as well?

**Comment by davidmarin** [comment]
Yes, there's an issue for this; see #1338.

**Comment by davidmarin** [comment]
Thanks for letting me know this is an issue for you!
