### ISSUE TITLE
Is auto-termination non-default in master?

### ISSUE THREAD

**Issue by thatdatabaseguy** [Yelp/mrjob#1642]
Hey @davidmarin - firstly thanks for mrjob! Using it at the moment to build [libpostal](https://github.com/openvenues/libpostal)'s increasingly large training set on Spark. The current job essentially does several planet-wide point-in-polygon tests on every polygon in OpenStreetMap (buildings, neighborhoods, cities, countries, etc.) and the "hydrated" addresses grow to about 100x the size of the original input, using a relatively large amount of disk space toward the latter part of the job, more than many of the instance types have locally.

As such, I wanted to try out the new `instance_groups` option for EMR in master in order to use instance types like R4 and specify a greater storage capacity without resorting to beefier, more expensive instance types.

Using the EBS-only instances did indeed solve the storage issue. However, I noticed that when switching to master, the clusters didn't seem to be terminated automatically when the jobs either completed or failed. Is that intentional and/or is there some other option that needs to be specified manually to auto-terminate?

**Comment by davidmarin** [comment]
In `master`, the default is to use cluster pooling, and for clusters to terminate themselves near the end of the billing hour if they've been idle for at least half an hour. So your clusters will eventually auto-terminate, but if you choose to run another job before the idle timeout is activated, you won't have to wait to provision a new cluster, and you'll get to use time on EMR that you would have been billed for anyway.

If your clusters don't *eventually* terminate themselves, please let me know; that would be a problem.

**Comment by thatdatabaseguy** [comment]
Ah ok, that makes sense. The cluster does indeed terminate after a little over an hour.
