### ISSUE TITLE
cannot import MRJob - SyntaxError in job.py

### ISSUE THREAD

**Issue by hongshaoyang** [Yelp/mrjob#1704]
I have `mrjob-0.6.0` installed on `Python 2.6.6` (which I cannot upgrade to 2.7). 

Doing a simple `from mrjob.job import MRJob` gives a `SyntaxError: invalid syntax`:

```
Traceback (most recent call last):
  File "reader.py", line 1, in <module>
    from mrjob.job import MRJob
  File "/zhome/f5/a/123662/.local/lib/python2.6/site-packages/mrjob/job.py", line 1106
    for k, v in unfiltered_jobconf.items() if v is not None
      ^
SyntaxError: invalid syntax
```

**Comment by davidmarin** [comment]
We dropped support for Python 2.6 in mrjob 0.6.0. Please upgrade to Python 2.7.

**Comment by hongshaoyang** [comment]
@davidmartin what is the latest version that supports Python 2.6?
