### ISSUE TITLE
local_tmp_dir ignored for running local

### ISSUE THREAD

**Issue by drpventura** [Yelp/mrjob#1710]
I have the following in my conf file:
```
runners:
  local:
    local_tmp_dir: temp
```
When I run my program from the command line, for example, `python mr_word_count.py --conf-path=mrjob.conf` it does not use the temp directory that is specified.  However, I have another section for emr that includes specifying the `local_tmp_dir: temp` and when I run it on emr, mrjob does use the specified temp directory.

I am using Python 3.6.2 on Windows 7 64bit with mrjob 0.6.0.

**Comment by davidmarin** [comment]
The default runner isn't `local`, it's `inline`. Try adding an `inline` section to your config.
