### ISSUE TITLE
max_mins_idle opt is blown away

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1726]
We set this to the default in `_fix_opts()` in `cloud.py`.

`_fix_opts()` looks at a single opt dict, not all opts as a whole, so it overwrites `max_mins_idle` anywhere where it's not set.

I'm not sure why I didn't just use `_default_opts()` in the cloud runner.

**Comment by dfdeshom** [comment]
FYI, this is the commit that erased `max_min_idle` from `_default_opts()`: https://github.com/Yelp/mrjob/commit/96a8e7f881efb28875044f06ce8e4ccc207a679e (part of https://github.com/Yelp/mrjob/pull/1695). It was in reference to this issue: https://github.com/Yelp/mrjob/issues/1693 .

**Comment by davidmarin** [comment]
This has been fixed.
