### ISSUE TITLE
`sys.stdin` , MRJob and Spark

### ISSUE THREAD

**Issue by dfdeshom** [Yelp/mrjob#1736]
Some MRJob Spark jobs trigger `sys.stdin` to be pickled (`MRJob` holds a reference to it via `self.stdin`). This in turn triggers a failure (since file handles are not serializable)  which leads to a long stack trace and the message `pickle.PicklingError: Cannot pickle standard input` message from Spark's `cloudpickle` package. 

I don't really know why this issue is appears only on certain kinds of jobs and not others. On simple jobs, things run fine. But for more complicated jobs, I keep running into this error. Here is an example of a job that is consistently failing for me: https://gist.github.com/dfdeshom/3865731e3fe36b79c7a1f516ddef9cc1 . 

Note that the job runs fine if I set `self.stdin` to `None` before doing anything.

**Comment by davidmarin** [comment]
I'm guessing the problem is that you're making Spark pickle instance methods, which reference the job instance itself, which includes sys.stdin.

In your example, I think you'd be okay if you made `merge_candidate_resume()` a staticmethod too.

**Comment by dfdeshom** [comment]
So looks like auxiliary functions should be defined outside of the class itself as functions or static methods (as opposed to plain class methods). Could this information be added somewhere on the Spark guide? https://pythonhosted.org/mrjob/guides/spark.html . The guide didn't mention that limitation and actually said that arbitrary code can be executed in the `spark()` method.

I can submit a PR for that if you want.
