### ISSUE TITLE
google-cloud is a very large dependency that is hard to install and can be replaced by google-auth and google-cloud-storage

### ISSUE THREAD

**Issue by firba1** [Yelp/mrjob#1746]
In particular, it ends up depending on google-gax, which is deprecated and also has a hard pin on ply, which makes it difficult to install with other libraries.

**Comment by davidmarin** [comment]
I think this may not be possible until `google-cloud-dataproc` 0.1.1 is out, as `google-cloud-dataproc`  has an incorrect limit on the version of `google-api-core`, only allowing 0.1.x versions even though the library is currently in 1.1.x.

In general, the dependencies for the various `google-cloud` libraries seem to be a bit brittle.

**Comment by firba1** [comment]
Wait I'm not sure how that's a blocker, since that's still an issue when depping google-cloud?

**Comment by davidmarin** [comment]
I'm not entirely sure. I think somehow it buries `google-cloud-dataproc`'s broken dependencies?

Basically, there's some sort of voodoo here going on that I don't fully understand. If you can figure out why, that would be very helpful.

**Comment by davidmarin** [comment]
Haha, silly GitHub, reverting a commit that says `fixes #...` doesn't count as fixing the issue.
