### ISSUE TITLE
multiple or shared SparkContext for each SparkStep?

### ISSUE THREAD

**Issue by vkchan** [Yelp/mrjob#1748]
I am new to MRJob/pySpark and I'm trying to implement a multi-step EMR/Spark job using MRJob, do I need to create a new SparkContext for each SparkStep, or can I share the same SparkContext for all SparkSteps?

I tried to look up the MRJob [manual](http://mrjob.readthedocs.io/en/latest/guides/spark.html) but unfortunately it was not clear on this.

Can someone please advise what's the correct approach? Thanks a lot!

1. Creating a separate SparkContext:

        class MRSparkJob(MRJob):
            def spark_step1(self, input_path, output_path):
                from pyspark import SparkContext
                sc = SparkContext(appName='appname')
                ...
                sc.stop()

            def spark_step2(self, input_path, output_path):
                from pyspark import SparkContext
                sc = SparkContext(appName='appname')
                ...
                sc.stop()

            def steps(self):
                return [SparkStep(spark=self.spark_step1),
                        SparkStep(spark=self.spark_step2)]

        if __name__ == '__main__':
            MRSparkJob.run()

2. Create a single SparkContext and share it among differnt SparkSteps

        class MRSparkJob(MRJob):
            sc = None

            def spark_step1(self, input_path, output_path):
                from pyspark import SparkContext
                self.sc = SparkContext(appName='appname')
                ...

            def spark_step2(self, input_path, output_path):
                from pyspark import SparkContext
                ... (reuse the same self.sc)
                self.sc.stop()

            def steps(self):
                return [SparkStep(spark=self.spark_step1),
                        SparkStep(spark=self.spark_step2)]

        if __name__ == '__main__':
            MRSparkJob.run()

**Comment by davidmarin** [comment]
If you want to have multiple spark steps, you should create a new SparkContext for each step. In essence, that’s what happens anyway, since each step is a completely new invocation of Hadoop and Spark.

However, the way Spark works, there isn’t much benefit into breaking it into two steps (other than to see the intermediate results for debugging).

**Comment by user2589** [comment]
@vkchan ,

I couldn’t find a better way to contact you so I’m writing here. This comment will be deleted in one week to keep the issue discussion clean.

My name is Marat, I am a PhD student at Carnegie Mellon University. As a part of my research, I’m trying to better understand the sources of issue reports in open source.

Can you please help me by answering few questions about this issue? It shouldn’t take more than a couple of minutes. Here’s the google form: [link](https://docs.google.com/forms/d/e/1FAIpQLSfTlhMeh25AZAr0wy-DNBki_HzFP_fqdT3eIk1mf7b80mg8Lg/viewform?usp=pp_url&entry.2074867396=https://github.com/Yelp/mrjob/issues/1748)

I will share everything I learn from answers to this survey with the community afterwards.

Thank you very much!
