### ISSUE TITLE
`max_mins_idle` does not work from mrjob.conf configuration file

### ISSUE THREAD

**Issue by naolenikhil** [Yelp/mrjob#1749]
`max_mins_idle` does not work from mrjob.conf file. mrjob/cloud.py, class HadoopInTheCloudJobRunner is called multiple times but does not associate `max_mins_idle` from mrjob.conf file bootstrap actions. As a result boostrap action -> idle timeout defaults to 10 min.

**Comment by davidmarin** [comment]
Which version are you on? I think this might be a duplicate of #1726, which has been fixed.

**Comment by davidmarin** [comment]
Closing this as a duplicate of #1726.
