### ISSUE TITLE
Client mode support for Spark on EMR

### ISSUE THREAD

**Issue by brenns10** [Yelp/mrjob#1756]
This is more of a question right now, based on my observations. I notice that we can only use Spark on EMR in cluster mode now (meaning the driver program is deployed on the cluster, rather than the spark-submit process). The [documentation](http://mrjob.readthedocs.io/en/latest/guides/spark.html?highlight=spark#running-on-emr) and [ticket](https://github.com/Yelp/mrjob/issues/1320) mention that this is because we cannot run tasks directly off of S3 in client mode ([EMR Docs](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-spark-submit-step.html)).

Running in cluster mode on EMR means that:
- The master instance is mostly unused. Since you're paying for it on-demand, this is a bit of a waste, and you need to be careful to select only the instance type that is necessary for maintaining your cluster.
- The driver program runs on the cluster. If your cluster is made up entirely of spot instances, your driver program has the potential to be terminated due to the spot market. This forces you to use at least one on-demand core node to host the driver program on the cluster, even if your job would run well otherwise on spot instances.

I don't have a very good understanding of mrjob's Spark integration, but would it be possible to sync application files (maybe in a bootstrap step?) to the master node so that client mode would be supported?

**Comment by davidmarin** [comment]
If Spark is running in a mode where it can't access S3, even getting an input manifest from your machine to the cluster would be tricky. You're better off just using at least one on-demand core instance.

Also, for what it's worth, mrjob already picks the smallest master node instance type that will work, unless you explicitly tell it otherwise with `--master-instance-type`.

**Comment by brenns10** [comment]
> If Spark is running in a mode where it can't access S3, even getting an input manifest from your machine to the cluster would be tricky. You're better off just using at least one on-demand core instance.

Internally we've been able to run Spark in client mode on EMR, for Jupyter notebooks. We've used bootstrap steps to copy our code to the cluster, so that we don't need to use s3 for the application files. Maybe that's a hack, but it doesn't seem like the S3 limitation is very big (but maybe that's just our use-case).

In any case, it's not the biggest deal, just a nice-to-have.

> Also, for what it's worth, mrjob already picks the smallest master node instance type that will work, unless you explicitly tell it otherwise with `--master-instance-type`.

Interesting, I did not know that. Thanks!
