### ISSUE TITLE
Reducer returning zero (key, value) output pairs

### ISSUE THREAD

**Issue by jtmzheng** [Yelp/mrjob#1797]
Can a mrjob reducer return zero pairs? 

https://pythonhosted.org/mrjob/job.html#mrjob.job.MRJob.reducer says a reducer should be implemented to "Yields one or more tuples of (out_key, out_value)", but the concepts section in https://media.readthedocs.org/pdf/mrjob/latest/mrjob.pdf implies a reducer should be able to return nothing: "A reducer takes a key and the complete set of values for that key in the current step, and returns zero or more arbitrary (key, value) pairs as output."

Thanks!

**Comment by davidmarin** [comment]
Yes, it can.
