### ISSUE TITLE
Exponential backoff can retry faster than the configured normal delay

### ISSUE THREAD

**Issue by bwbaugh** [Yelp/mrjob#1799]
The exponential backoff is hard coded to start at 20 seconds.

https://github.com/Yelp/mrjob/blob/54dc657fe204081c3af82c83a1d7d1ee47422dae/mrjob/fs/s3.py#L51

The default delay for checking the status of a mrjob is 30 seconds. If we are throttled after 30 seconds, then we will initially actually be calling AWS more quickly until the backoff progresses.

When using the default value of 30 seconds, this isn’t so bad. However, when setting `check_cluster_every` to something much higher (to avoid throttling errors when running many jobs on the AWS account) then starting the retry back at 20 seconds means the problem is going to get worse before it gets better.

**Comment by davidmarin** [comment]
Yeah, we should make sure the initial backoff is at least `check_cluster_every`. I think keeping a floor of 20 seconds still makes sense.

**Comment by davidmarin** [comment]
Also, only applying this to EMR; it's hard to make a case that `check_cluster_every` is relevant to S3, IAM, etc.

**Comment by davidmarin** [comment]
It looks like in practice, boto3 is pretty good at handling throttling client errors from the EMR API; we're mostly going to be handling socket errors and the like.
