### ISSUE TITLE
support custom AMIs

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1805]
Should add support for the `CustomAmiId` param. Probably should call the corresponding option `image_id`, and check for a custom image ID when pooling.

For more details, see: https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-custom-ami.html

**Comment by davidmarin** [comment]
Successfully hand-tested this!

**Comment by davidmarin** [comment]
@marksimpson82 this is in `master`, if you'd like to try it out.

**Comment by marksimpson82** [comment]
Thanks. I'm on holiday at the moment, will give it a go when back next week!
