### ISSUE TITLE
[Information] setting mrjob to read only first parameter of stdin

### ISSUE THREAD

**Issue by giupardeb** [Yelp/mrjob#1834]
Hi all, how can I force mrjob to read only first parameter of stdin? 
Thank you!

**Comment by davidmarin** [comment]
Sorry, I'm not sure I understand the question. You mean to make mrjob's mapper only read the first record on each line?

**Comment by giupardeb** [comment]
No, For Example, if I launch this:

python main.py file.txt pluto.txt 

I want that mrjob's mapper will only read the first parameter of stdin.

**Comment by davidmarin** [comment]
Sorry, do you want it to read a filename from stdin?

**Comment by pietrobiondi** [comment]
I have got the same problem.

In practice, we want that mrjob will read only the first arg from the stdin. 

For example, if we have:
`python mymrjobproject.py file1.txt /mypath/mydir mysysarg3`

we want mrjob will read and execute map-reduce only to "file1.txt"



At this moment, if I try to launch the mrjob project.. the program tries to apply map-reduce to all 3 argument and return me an error.

Let me know if it's clear.
Thank you.

**Comment by davidmarin** [comment]
Ah, okay, you want it to only read the first argument from the command line. Why not just pass a single argument, instead of three?

**Comment by pietrobiondi** [comment]
Because I need the other two arguments for other operations of my program.

So, is not possible to say to Mrjob: "read only first argument" ?

**Comment by davidmarin** [comment]
Generally, if you want to pass non-input arguments into mrjob, you use switches. See https://mrjob.readthedocs.io/en/latest/guides/writing-mrjobs.html#defining-command-line-options.

You can also write a separate job that launches a mrjob (which can then take arguments in any format it wants). See https://mrjob.readthedocs.io/en/latest/guides/runners.html#running-your-job-programmatically

**Comment by lmyyao** [comment]
> Generally, if you want to pass non-input arguments into mrjob, you use switches. See https://mrjob.readthedocs.io/en/latest/guides/writing-mrjobs.html#defining-command-line-options.
> 
> You can also write a separate job that launches a mrjob (which can then take arguments in any format it wants). See https://mrjob.readthedocs.io/en/latest/guides/runners.html#running-your-job-programmatically

hi ,  i don't want stdin/input as first parameter, can you give an example ? thanks
