### ISSUE TITLE
Permission Error [WinError 5] on windows

### ISSUE THREAD

**Issue by Drulludanni** [Yelp/mrjob#1847]
the reason for this is that the temp file that is created gets its write permissions modified by this piece of code in `mrjob/sim.py`

```
def _chmod_u_rx(path, recursive=False):
    """make *path* user readable and executable. If *recursive* is true,
    make *path* and everything inside it executable."""
    if recursive:
        for dir_name, _, file_names in os.walk(path, followlinks=True):
            for file_name in file_names:
                _chmod_u_rx(join(dir_name, file_name))
    else:
        if hasattr(os, 'chmod'):  # only available on Unix, Windows
            os.chmod(path, stat.S_IRUSR | stat.S_IXUSR)
```

Which will cause shutil.rmtree(path) to fail later when cleaning up the temp directory.

A simple example to see this failure is by running this piece of code
```import os
import  stat

filename = "test_file.txt"
with open(filename,"w") as file:
    file.write("aaaa")

os.chmod(filename, stat.S_IRUSR | stat.S_IXUSR)
os.remove(filename)
```
Which will also fail for the same reason on windows. 
is there a reason for chmodding the file? Is it possible to change the code such that
```
if hasattr(os, 'chmod') and os.name != 'nt':  # disabled for windows due to issues with deleting the temp folder
    os.chmod(path, stat.S_IRUSR | stat.S_IXUSR)```
so that it works on windows and doesn't crash + leave garbage behind in the temp folder?

**Comment by davidmarin** [comment]
Oh, interesting. I'm guessing that on Windows, `rmtree()` expects the file to have `stat.S_IWUSR` to be able to remove it.

This code exists to imitate the way Hadoop sets permissions on distributed cache files. It won't break anything to disable it on Windows.

Would you like to submit a pull request? mrjob uses `platform.system() == Windows` to detect Windows, but otherwise your code looks good.

**Comment by Drulludanni** [comment]
Yeah, I'll do it.

**Comment by davidmarin** [comment]
Thanks! Sorry I'm not able to support Windows better.
