### ISSUE TITLE
Problem running JarStep (s3distcp) on EMR: extra args supplied to the jar

### ISSUE THREAD

**Issue by artem-cliqz** [Yelp/mrjob#1863]
version: 0.6.5

I am running spark and hadoop streaming jobs on the same EMR cluster. `JarStep` below is used to copy data from hdfs to s3. Config contains configuration for hadoop. Hadoop config flags are passed to the jar. The flags are not expected by `script-runner.jar` and it fails with message `Exception in thread "main" java.lang.RuntimeException: Local file does not exist.`

```
JarStep(
    jar='s3://elasticmapreduce/libs/script-runner/script-runner.jar',
    args=[
        '/usr/bin/s3-dist-cp',
        '--src',
        INPUT,
        '--dest',
        OUTPUT,
    ]
)
```

In EMR web console the result is seen as longer list of args to the Jar. Below are desired and actual values from EMR console.

Desired:
```
JAR location : s3://elasticmapreduce/libs/script-runner/script-runner.jar
Main class : None
Arguments : /usr/bin/s3-dist-cp --src s3://test-bucket/path1/ --dest s3://test-bucket/path2/
Action on failure: Terminate cluster
```

Actual:
```
JAR location : s3://elasticmapreduce/libs/script-runner/script-runner.jar
Main class : None
Arguments : -D mapreduce.map.output.compress=true -D mapreduce.map.output.compress.codec=org.apache.hadoop.io.compress.GzipCodec -D mapreduce.output.fileoutputformat.compress=true -D mapreduce.output.fileoutputformat.compress.codec=org.apache.hadoop.io.compress.GzipCodec -D mapreduce.output.fileoutputformat.compress.type=BLOCK /usr/bin/s3-dist-cp --src s3://test-bucket/path1/ --dest s3://test-bucket/path2/
Action on failure: Terminate cluster
```

I believe this is the line that causes a problem: https://github.com/Yelp/mrjob/blob/master/mrjob/emr.py#L1338
I am not sure if something else relies on current behaviour. 

A quick and ugly solution I use is patching EMRJobRunner. 
```python
def patch(fun):
    def patched(*args, **kwargs):
        response = fun(*args, **kwargs)
        if response['Jar'] == 's3://elasticmapreduce/libs/script-runner/script-runner.jar':
            while len(response['Args']) > 0 and response['Args'][0] == '-D':
                response['Args'] = response['Args'][2:]
        return response
    return patched

from mrjob.emr import EMRJobRunner
EMRJobRunner._jar_step_hadoop_jar_step = patch(EMRJobRunner._jar_step_hadoop_jar_step)
```

Could you provide a rationale why hadoop args are passed to Jar in `JarStep`? What would you suggest as a permanent fix for the problem?

**Comment by davidmarin** [comment]
Oh, that's interesting. It's just trying to set configuration properties, but apparently that doesn't play well with script-runner.jar. I'll look into it.

**Comment by davidmarin** [comment]
I'm going to try passing in the configuration properties through the `Properties` param to [AddJobFlowSteps](https://docs.aws.amazon.com/emr/latest/APIReference/API_AddJobFlowSteps.html) in the EMR API, rather than passing in `-D` arguments.

If that doesn't work with `script-runner.jar` either, I'll special-case it.

**Comment by davidmarin** [comment]
Attempting to duplicate this now.

At least in theory, any jar passed to the `hadoop jar` command is supposed to be able to support generic args such as `-D` and `-libjar`. Looks like not, in practice.

It may be that special-casing script-runner.jar and command-runner.jar is the best solution.

**Comment by davidmarin** [comment]
Probably the best way to solve this would be to add a `generic_options` property to mrjob's `JarStep` that specifies whether the jar accepts `-D` and other generic arguments.

**Comment by artem-cliqz** [comment]
👍 It would be nice if the value could be provided in constructor like:
```python
JarStep(
    jar='s3://elasticmapreduce/libs/script-runner/script-runner.jar',
    args=[
        '/usr/bin/s3-dist-cp',
        '--src',
        INPUT,
        '--dest',
        OUTPUT,
    ],
    generic_args=False,  # or add_generic_args=False
)
```

**Comment by davidmarin** [comment]
It looks like `hadoop-mapreduce-examples.jar` doesn't accept `-D` either. So probably the best thing to do is just turn this off for jar steps.

**Comment by davidmarin** [comment]
You know, I think I'll create a `GENERIC_ARGS` constant that can be interpolated into `args` instead. Sometimes the generic args work, but not as the first arguments after `jar`. For example, the hadoop example jar accepts them *after* the name of the example:

```
hadoop jar hadoop-mapreduce-examples.jar pi -D foo=bar 10 20
```

**Comment by davidmarin** [comment]
It's in `master`. Try it out!

**Comment by artem-cliqz** [comment]
Will do! Thanks for taking care of it!

**Comment by davidmarin** [comment]
Sure, thanks for letting me know there was a problem!

**Comment by artem-cliqz** [comment]
Works in our setup: on a cluster configured to run spark / hadoop streaming jobs. Thanks again for the fix!
