### ISSUE TITLE
add_file_option options should support S3 paths

### ISSUE THREAD

**Issue by smartt** [Yelp/mrjob#192]
I'm using 'add_file_option' to include a sqlite3dbm file containing data that my map/reduce jobs need.  It works fine like this:

`python mymrjob.py -r emr --my-custom-file=data/foobar.db file_to_parse.json`

But not like this:

`python mymrjob.py -r emr --my-custom-file=s3://mybucket/data/foobar.db s3://mybucket/file_to_parse.json`

As my custom file option file grows larger, I'd prefer to simple store it on S3 and have it pulled to the Hadoop machines, rather than uploading said file from my machine.

**Comment by davidmarin** [comment]
Not going to do this. The way to make this work is to load the file as needed, rather than in `__init__()`.
