### ISSUE TITLE
import error when using Hadoop

### ISSUE THREAD

**Issue by NNNNNaaaaaa** [Yelp/mrjob#1996]

**Comment by NNNNNaaaaaa** [comment]
I need to import networkx in my script,  when I run with Hadoop, ImportError: No module named networkx

**Comment by davidmarin** [comment]
Yes, mrjob just makes sure your script and the mrjob library get onto your cluster; the rest is up to you.

A simple way to get networkx is to download the networkx egg file and run your script with `--py-files networkx.<version>.egg`.

For other ways, see https://mrjob.readthedocs.io/en/stable/guides/setup-cookbook.html
