### ISSUE TITLE
simplify setup/bootstrap cmds/scripts/actions

### ISSUE THREAD

**Issue by coyotemarin** [Yelp/mrjob#206]
`mrjob` has a lot of options that are designed to upload a file, run a command, or add something to the environment:
- bootstrap_actions
- bootstrap_cmds
- bootstrap_files
- bootstrap_mrjob
- bootstrap_python_packages
- bootstrap_scripts
- file_upload_args (not available from the command line)
- python_archives
- setup_cmds
- setup_scripts
- upload_archives
- upload_files

There are two main problems with the way things are now:
- It's confusing
- Options don't always run in the order you want. For example, if you upgrade Python in `bootstrap_cmds`, `bootstrap_python_packages` becomes useless because it runs first (so it'll install packages for the old version of Python).

I don't have a complete solution, but I imagine something where you simply specify the commands you want to run, possibly referencing local paths or S3/HDFS URIs, and `mrjob` just does the right thing. We just need a clean way of disambiguating local and remote files.

We should aim to make this solution the canonical way of doing things in `mrjob` v0.4.

**Comment by davidmarin** [comment]
Noting that I never actually implemented globs (for local or remote files). #938 is now the ticket for this.
