### ISSUE TITLE
Broadcast variables for the next MRJob

### ISSUE THREAD

**Issue by kno10** [Yelp/mrjob#2076]
In a multi-step MapReduce job, it may be necessary that one job produces some shared "parameters" for the next job.
For example, when implementing the well-known HITS algorithm <https://en.wikipedia.org/wiki/HITS_algorithm> - a variant of PageRank that distinguishes hubs and authorities - we need to normalize all values after each iteration. It would be fairly easy to produce the normalization term in one iteration along with the data (e.g., by outputting to a special normalization key). However, I could not find a way to broadcast this value afterwards to the next MRJob to perform this normalization.
The basic idea is to have some variables / files that can be written to during the job, but the new value is not available until the _next_ job. Between of the two jobs, the platform would then need to distribute this value, so obviously one should only use this for small data, such as parameters. In this case, the normalization term would be a single double that needs to be passed from MRJob step n to MRJob step n+1.
The current --files option is not enough, because the data changes between different steps.

**Comment by davidmarin** [comment]
Broadcasting global variables is not really Hadoop Streaming's strong suit.

If you do want to do this with Hadoop Streaming, the key is having an external script that launches jobs (see https://mrjob.readthedocs.io/en/latest/guides/runners.html#running-your-job-programmatically). You'd probably want one job that performs a step of HITS, and another one that can produce the normalization term (and possibly information that tells you when the algorithm has converged). 

Alternatively, you could use Spark, which is pretty great at broadcasting global variables and iterating on something *n* times. mrjob works great with Spark (see https://mrjob.readthedocs.io/en/latest/guides/spark.html).

**Comment by kno10** [comment]
Streaming the output from one job to another means creating a bottleneck, so that is not what you'd want to use. MapReduce already is a pain here, because the graph doesn't change, only the node weights, and is written to disk repeatedly, unless it fits into a file.
Yes, Spark is much more appropriate here, but then probably without mrjob, but pure spark.
I was looking for examples on what to do with MapReduce except the word count and grep examples everybody uses, and I am quite disappointed that apparently HITS is already too complex. :-(
