### ISSUE TITLE
"UnboundLocalError: local variable 'task_error' referenced before assignment"

### ISSUE THREAD

**Issue by shrikantkrd14** [Yelp/mrjob#2096]
Hi,

I am getting error "UnboundLocalError: local variable 'task_error' referenced before assignment" while running mrjob on AWS EMR. I am using map-reduce for structuring the data for solar index. The strange thing is that, It only fails  after running some 1000 documents. I don't understand, from where I can pass the value for "task_error".

I am using mrjob version 0.5.6.

Please help.

**Comment by davidmarin** [comment]
I think this is a known issue, but it's an issue in a version of mrjob that's nearly three years old at this point. I recommend upgrading to the latest version (v0.6.10), or, if that doesn't work, the latest 0.5.x version, v0.5.12.
