### ISSUE TITLE
Make terminate_idle_clusters accept list of filters, exit non-zero on failure to terminate

### ISSUE THREAD

**Issue by stug** [Yelp/mrjob#2109]
To make it easier to alert when we are failing to kill idle clusters, it would be nice if `terminate_idle_clusters` returned a non-zero exit code when it can't kill a cluster.

However, because sometimes there are idle clusters that we know about and want to keep around, can we also add the ability to filter clusters by name (or tag?) so that we'll only exit with a non-zero code if there's an idle cluster that we can't kill that we weren't expecting?

**Comment by davidmarin** [comment]
I need to make an 0.6.12 to fix a severe but simple Google Cloud Dataproc issue (see #2110), so might as well have this in an 0.6.x release as well.

**Comment by stug** [comment]
Thanks!

**Comment by davidmarin** [comment]
Dropping this ticket for now. `terminate-idle-clusters` could certainly be improved, but this ticket is actually tied to a very particular use case that was worked around in another way (grepping the debug log of the script).
