### ISSUE TITLE
Dataproc initialization error

### ISSUE THREAD

**Issue by amitabhchaudhary** [Yelp/mrjob#2110]
On running a simple word frequency job on Dataproc, the dataproc-initialization-script-0_output reports

"E: Failed to fetch http://security.debian.org/pool/updates/main/e/expat/libexpat1-dev_2.2.0-2+deb9u1_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"

Attaching below (1) Dataproc initialization script output, (2) mrjob terminal output, (3) word frequency python file used, (4) word frequency data file used. 

[google-cloud-dataproc-metainfo_745ceb00-3a4a-4e74-a01d-42dee742d853_mrjob-us-west1-ec1a420d3930d4d3-m_dataproc-initialization-script-0_output.txt](https://github.com/Yelp/mrjob/files/3695547/google-cloud-dataproc-metainfo_745ceb00-3a4a-4e74-a01d-42dee742d853_mrjob-us-west1-ec1a420d3930d4d3-m_dataproc-initialization-script-0_output.txt)
[mrjob.log.txt](https://github.com/Yelp/mrjob/files/3695548/mrjob.log.txt)
[word_freq.py.txt](https://github.com/Yelp/mrjob/files/3695549/word_freq.py.txt)
[data1.txt](https://github.com/Yelp/mrjob/files/3695550/data1.txt)

**Comment by davidmarin** [comment]
I think this is just because the default image version for Dataproc hasn't been updated in forever (see https://cloud.google.com/dataproc/docs/concepts/versioning/overview).

I'll update this in v0.7.0, but in the meantime, please try running scripts with `--image-version 1.4.14` as a workaround.

**Comment by davidmarin** [comment]
Actually, it would be good to have this fixed in an 0.6.x version, moving to 0.6.12

**Comment by davidmarin** [comment]
I was able to make a job run with `--image-version 1.3`. The latest image version, 1.4, doesn't seem to work with mrjob, some problem with bootstrapping the mrjob library.
