### ISSUE TITLE
Spark cluster stalls on EMR when using defaults

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#2130]
Even in mrjob 0.7.0, it's still possible to launch a Spark cluster that's too small to run. Should find out what defaults work on the latest AMIs.

**Comment by davidmarin** [comment]
Was unable to duplicate this. Maybe EMR quietly fixed their cluster configs? Closing for now.

**Comment by 88manpreet** [comment]
I think you planned to close this. Closing.
