### ISSUE TITLE
Override SparkStep's input_path

### ISSUE THREAD

**Issue by milosjajac** [Yelp/mrjob#2144]
In a multi-spark-step program, is it possible to override the `input_path` of the steps? For example, here is the code:

```python
class MRSparkWordcount(MRJob):
    
    def steps(self):
        return [
            SparkStep(spark=self.spark_step_1),
            SparkStep(spark=self.spark_step_2)
        ]

    def spark_step_1(self, input_path, output_path):
        from pyspark import SparkContext
        # some code...
        stuff.saveAsTextFile(output_path)
        sc.stop()

    def spark_step_2(self, input_path, output_path):
        from pyspark import SparkContext
        # input_path here is the output_path from spark_step_1
        sc.stop()

if __name__ == '__main__':
    MRSparkWordcount.run()
```

I know it makes sense that the `spark_step_2` uses the previous step's output as its input, but is it possible to somehow override/set this? For example, I would like step 1 to use directory A is input and B as output, and step 2 to use directory C as input (_not_ B) and D as output. Does this have to be modeled as separate `MRJob`s or?

**Update:**

I found this method in mrjob's `runner.py`:

```python
    def _step_input_uris(self, step_num):
        """A list of URIs to use as input for the given step. For all
        except the first step, this list will have a single item (a
        directory)."""
        if step_num == 0:
            return [self._upload_mgr.uri(path) if self._upload_mgr
                    else to_uri(path)
                    for path in self._get_input_paths()]
        else:
            return [to_uri(self._intermediate_output_dir(step_num - 1))]
```

So I guess the `input_path` of all steps following the first one cannot be set?

**Comment by davidmarin** [comment]
Yes and no. mrjob’s step model is intentionally very simple; the output of one step is the input of the next.

However, in Spark you can read from or write to wherever you like. mrjob provides the input and output path to your spark() method(s) as a convience to you, but you can do whatever you like with them.

I’d recommend you either write a single spark() method, or just write an ordinary Spark script and launch it with `mrjob spark-submit`.

-Dave

**Comment by milosjajac** [comment]
I see, makes sense. Thank you for a very prompt reply and for the suggestions.
