### ISSUE TITLE
Suggestion: Add an option to accept empty lines in json 

### ISSUE THREAD

**Issue by alexandra-trisch** [Yelp/mrjob#2148]
I'm using mrjob to process a number of json lines, where some lines might be empty. If I'm using `JSONValueProtocol` for input it obviously fails the whole mapper. 

As workaround I do use Raw protocol and parse json line inside mapper.

Is there an option to use `JSONValueProtocol` with some settings or maybe we could use during load default `json.loads(line or '{}')`

**Comment by davidmarin** [comment]
Protocols can't skip lines; the assumption is that every line will include a key and value.

You could subclass `JSONValueProtocol` to return a `None` value when the line is empty though.
