### ISSUE TITLE
Spark harness is not populating counters when counter-output-dir is not an S3 path

### ISSUE THREAD

**Issue by 88manpreet** [Yelp/mrjob#2176]
[Hadoop Counters](https://data-flair.training/blogs/hadoop-counters/), an integral feature of Hadoop map-reduce provides a way to measure the progress or the number of operations that occur within map/reduce job.
[Spark harness runs](https://github.com/Yelp/mrjob/wiki/How-mrjob-works#the-spark-harness) the regular hadoop streaming job on spark using Spark Runner.
Spark harness emulates the [counters feature](https://mrjob.readthedocs.io/en/latest/guides/spark.html#counter-emulation-is-almost-perfect) to run the same hadoop-streaming job onto spark without requiring any modifications to the job.
Harness script stores the calculated counters value to the given counter_output_dir (--spark-tmp-dir) using [saveAsTextFile](https://github.com/Yelp/mrjob/blob/master/mrjob/spark/harness.py#L287) spark api. The populated counters values is in turn read by [spark runner](https://github.com/Yelp/mrjob/blob/master/mrjob/runner.py#L663) to be provided to application user.
The logic works well if the the path for `--spark-tmp-dir` is an S3 path. With the regular local file-path (by default), `saveAsTextfile` creates the counters file (part-*) on spark executors but not on the driver local file-path. Unless, the executors are running on the same host as drivers.

**Comment by davidmarin** [comment]
Fixed by #2177.
