### ISSUE TITLE
bootstrap cmds run after bootstrap python modules

### ISSUE THREAD

**Issue by Roguelazer** [Yelp/mrjob#251]
Let's say, just hypothetically, that you wanted to use a python module on EMR which required a bunch of system modules to build. Say, a library like M2Crypto, which depends on libssl and swig. So you go about your business of adding a bootstrap_cmd of `sudo apt-get install libssl-dev swig`, and adding a boostrap_python_module of `module.tar.gz`. All set, right?

**wrong**

mrjob apparently runs bootstrap cmds _after_ running the python module builds. Which is, of course, backwards for these purposes.

I imagine that existing configs would be broken by reversing this (I could imagine a case where you want your bootstrap_cmd to use a python module that you just built), so maybe it would best to have an `early_bootstrap_cmd` option? Anyhow, just another annoyance on the road of mrjob.

**Comment by davidmarin** [comment]
`bootstrap_cmds` was removed in mrjob v0.6.0 and I believe `bootstrap_python_packages` was removed in v0.5.0. Issue resolved!
