### ISSUE TITLE
Parse/display failed bootstrap action stderr

### ISSUE THREAD

**Issue by irskep** [Yelp/mrjob#370]
mrjob currently gives very unhelpful errors for failed bootstrap, and yet there is a fairly obvious place to pull errors from: bootstrap-actions/#/node-*/stderr. We should at least dump a list of relevant paths to the user.

**Comment by zachm** [comment]
@davidmarin looks like the issue I was telling you about earlier already exists! It'd be great to have this - I can take a whack at it eventually if you have more pressing issues.

**Comment by davidmarin** [comment]
@zachm, that would be great (and I'm happy to answer questions or give advice). It's really important to me to get v0.5.0 out, so I can't put nice-to-have features on my plate until that happens.

**Comment by davidmarin** [comment]
Sometimes there's a hint about what went wrong in `stdout`, for example:

```
Compiling /usr/lib/python2.6/dist-packages/mrjob/logs/history.py ...
SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/dist-packages/mrjob/logs/history.py', 255, 54, '            if not (isinstance(amount, integer_types):\n'))
```

Not sure how to handle this in a systematic way.

**Comment by davidmarin** [comment]
I think the thing to do is to redirect stdout into stderr. Because we tell the shell to echo, we can just show the last command and its stdout/stderr.
