### ISSUE TITLE
Distinguish between mapper and reducer counters when parsing/printing

### ISSUE THREAD

**Issue by irskep** [Yelp/mrjob#465]
We currently read the aggregate COUNTER field of a job's output. We should also dump MAP_COUNTERS and REDUCE_COUNTERS separately.

**Comment by davidmarin** [comment]
This is actually probably a bad idea. It looks like we won't be able to get counters separated by map/reduce when we fetch them from S3 when using 3.x AMIs is; see [this comment](https://github.com/Yelp/mrjob/issues/888#issuecomment-136559209).

So, resolving this issue by deciding not to do it. Success!

**Comment by davidmarin** [comment]
It looks like the YARN history file (which is normally stored on HDFS!) has separate map/reduce counters, if we ever want to do this.
