### ISSUE TITLE
Investigate using tox for tests

### ISSUE THREAD

**Issue by irskep** [Yelp/mrjob#516]
> Tox is a generic virtualenv management and test command line tool you can use for:
> - checking your package installs correctly with different Python versions and interpreters
> - running your tests in each of the environments, configuring your test tool of choice
> - acting as a frontend to Continuous Integration servers, greatly reducing boilerplate and merging CI and shell-based testing.

http://tox.testrun.org/latest/

Given that we support 3 versions of Python and have two optional dependencies, this could be useful.

**Comment by davidmarin** [comment]
Happy with Travis CI for now. Travis CI docs indicate that running Tox inside Travis is complicated: https://docs.travis-ci.com/user/languages/python/#using-tox-as-the-build-script
