### ISSUE TITLE
Not uploading archives to hadoop

### ISSUE THREAD

**Issue by timtadh** [Yelp/mrjob#564]
I am experiencing an issue where mrjob is not uploading archives correctly to hadoop. The archive is correctly being unpacked by the local runner, however when run on hadoop it appears that it never makes it off of HDFS.

The situation

    python job.py ... --archive=archive.tar.gz ... -r hadoop

result

    hdfs:///some/path/archive.tar.gz

however in the "jobcache" working dir does not contain the archive either unpacked or packed.

I am will to do some digging but I need some pointers for where to look I got stuck at line 375 in mrjob/runner.py, which is where I decided to stop looking for the night and just submit and issue and worry about this tomorrow.

-Tim

**Comment by davidmarin** [comment]
Pretty sure this is fixed.

**Comment by timtadh** [comment]
Probably. I don't use hadoop anymore so I can't test it.
