### ISSUE TITLE
Use <output_dir>/_logs in Hadoop

### ISSUE THREAD

**Issue by tarnfeld** [Yelp/mrjob#565]
The [`counters()`](https://github.com/Yelp/mrjob/blob/master/mrjob/hadoop.py#L468) method returns nothing. By the looks of things, when the job completes and the `_fetch_counters()` method is called, it assumes you're running mrjob on the job tracker node (I think) and the logs directory is on the local disk. When running on a remote hadoop cluster, the local logs/history directory doesn't exist where mrjob is being run and therefore no logs/counters are found.

By the looks of things, the counters can also be found in the `_logs` directory of a successful job.

**Comment by wayoutmind** [comment]
+1

**Comment by davidmarin** [comment]
Will look into this.

**Comment by tarnfeld** [comment]
Just a reminder that we've got patches for this fix further up in the comments (from 2 years ago 😱)

**Comment by davidmarin** [comment]
Sorry to take so long to get to this. I'm partway through revamping the log parsing system, and it should be pretty easy to add once I do that.

I'm more worried about testing; it looks like `_logs` in the output dir is a Cloudera-specific feature. What's the easiest way for me to get Cloudera up and running so I can poke at it?

**Comment by davidmarin** [comment]
Looks like I should try out `[Cloudera Live](http://www.cloudera.com/content/www/en-us/developers/get-started-with-hadoop-tutorial.html)`.
