### ISSUE TITLE
Only sort values in local/inline mode if asked to

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#660]
Currently, we just use `sort` to simulate the reducer.

This can produce unexpected results because when running a job locally, lines will be essentially be sorted by key and then value (like #240 is supposed to support), whereas Hadoop only sorts by key.

Unless the job sets `SORT_VALUES`, local and inline mode should _not_ sort by value. Probably the most portable way to do this  (i.e. that works with BSD and GNU sort)  is something like `sort -k 1 -t "\t" -s`, which sorts by the first field up to the first tab, and then does a stable sort.

We'll need to fall back to just plain `sort` so it'll still work on Windows.

**Comment by tomwarrens** [comment]
Hi, is this issue closed or moved to another branch? 

thanks
