### ISSUE TITLE
Explain *_cmd better and make docs more accessible

### ISSUE THREAD

**Issue by irskep** [Yelp/mrjob#703]
In particular, it's not clear why the examples use `bash_wrap()`, it's not obvious that `*_cmd()` is available as an argument to `mr()`, and it's never specified what those arguments should contain (i.e. strings).

**Comment by davidmarin** [comment]
Fixed. See for example https://mrjob.readthedocs.io/en/latest/job.html#mrjob.job.MRJob.mapper_cmd
