### ISSUE TITLE
future-proof EMR SSL certs

### ISSUE THREAD

**Issue by coyotemarin** [Yelp/mrjob#706]
The host on the SSL certificates for EMR (`<region>.elasticmapreduce.amazonaws.com`) is different from the host in the [AWS documentation](http://docs.aws.amazon.com/general/latest/gr/rande.html#emr_region) (`elasticmapreduce.<region>.amazonaws.com`).

Pull request #705 changes us over from the host in AWS's documentation to the host that matches the SSL certificates, which should fix #621.

However, this makes me very nervous. The documentation is wrong now, but someday it may be right, and then mrjob will not work correctly.

What we should do, before we release v0.4.1, is something I mentioned in #658: wrap the connections in such a way that we first try the host in the documentation, and if we get an SSL error, we fall back to the host that we know matches the SSL certs.

**Comment by davidmarin** [comment]
Huh, this still hasn't been "fixed". The documentation still says `elasticmapreduce.<region>.amazonaws.com` and the certificate still ways `<region>.elasticmapreduce.amazonaws.com` (checked this in a web browser; just go to `https://<host>` and then click on the green lock.

There's some other field in the certificate that makes this OK for web browsers, but it's probably not okay for Python's SSL code.
