### ISSUE TITLE
Make it easier to override job_runner_kwargs()

### ISSUE THREAD

**Issue by irskep** [Yelp/mrjob#740]
If I want to specify `upload_files` for just one job, I'd like to be able to do this:

``` python
class MyJob(MRJob):

    def runner_kwargs(self):
        {'upload_files': ['/some/path']}
```

One use case would be a job that needs a sqlite database but never needs its local path passed on the command line.

**Comment by davidmarin** [comment]
This use case is now solved by the `FILES` attribute (see #1431).
