### ISSUE TITLE
deprecate self.mr() in favor of mrjob.step.MRStep

### ISSUE THREAD

**Issue by coyotemarin** [Yelp/mrjob#815]
_MRStep used to be named MRJobStep; renaming it in my [hadoop_jar_io](https://github.com/davidmarin/mrjob/tree/hadoop_jar_io) branch._

Using `self.jar()` to access `self.step.JarStep` doesn't make much sense now that we interpolate input and output (#773), since you need access to `JarStep.INPUT` and `JarStep.OUTPUT` to really make it function as part of a job.

So, let's aim for consistency in the other direction, and have people use `MRStep` instead. It's one character shorter, and it's clearly not something you're supposed to override in your `MRJob` subclass. And if you're enough of a power user to override `steps()`, you can handle an additional import.

I can't imagine _removing_ `mr()` in the near future since it's been part of mrjob from the beginning, but we could say it'll be removed in v0.6.0 or some such.

**Comment by yingbo** [comment]
Any good example showing how to switch?
