### ISSUE TITLE
path_exists does not exist for HadoopJobRunner

### ISSUE THREAD

**Issue by hesenp** [Yelp/mrjob#850]
Hi there, 

[This is my first time to submit issues in github. So please forgive me for the possible missing info]. 

I found MRJob possibly unusable in hadoop mode due to a missing method to the HadoopJobRunner. In line 249 of mrjob.hadoop.py, the object will check via self.path_exists, where the method path_exists does not exist in the code at all. I tried to fix that myself but it seems there's quite a few other bugs out there as well. Let me label this one first. 

Hesen

**Comment by davidmarin** [comment]
Figuring this was fixed by #860.
