### ISSUE TITLE
don't validate all keys on S3 buckets

### ISSUE THREAD

**Issue by coyotemarin** [Yelp/mrjob#865]
`boto.s3.connection.S3Connection.get_bucket()` apparently validates _all_ keys on a bucket before allowing us to use it, which makes mrjob block for no reason when working with a bucket with a lot of keys. This was fixed in boto 2.25.0. See http://www.appneta.com/blog/s3-list-get-bucket-default/ for more details.

We just need to always call `get_bucket()` with `validate=False`. This works all the way back to 2.2.0, which is the earliest version mrjob 0.4.x allows.

**Comment by prat0318** [comment]
Just a quick question. How can i pass `validate=False` from mrjob as this is what i am running:
```
python word_count.py -r emr --s3-scratch-uri=s3://q/p/tmp/ word_count.py
```
There is no place where i am manually calling `get_bucket`. Currently, the hack i am using is to change the mrjob library: `util.py`
``` 
VALIDATE_BUCKET = False #boto and boto.Version >= '2.25.0'
```
