### ISSUE TITLE
Invalid bootstrap action path, must be a location in Amazon S3

### ISSUE THREAD

**Issue by whatsdis** [Yelp/mrjob#899]
I see that the issue https://groups.google.com/forum/#!topic/mrjob/KV_FGdcwJKo was addressed with the recent code update with the new method `is_windows_path(uri)` however, I am still getting the exact same error message on windows 7 machine.

Excerpt from that thread: 

When I run my python word_count.py mytext.txt it works locally. No errors. 
When I run python word_count.py -r emr mytext.txt, it doesn't work.
It starts kind of. and then, after "Creating Elastic MapReduce job flow" fails with long list if stuff, final message inside XML of which is: 
"Invalid bootstrap action path, must be a location in Amazon S3"

**Comment by davidmarin** [comment]
I believe this has been fixed by #866 and will be in the next release.
