### ISSUE TITLE
Unknown command -e

### ISSUE THREAD

**Issue by andr0s** [Yelp/mrjob#900]
There's a bug in the PIP version that has not been fixed yet (as I understood) in the master branch.

Using hadoop 2.40, the reducer step failed because of the error in the title.

Ubuntu 13.10 x64, if important.

Local hadoop installation (-r hadoop args). But maybe EMR also affected.

The quick and dirty patch:

mrjob/inline.py - method _run_steps(),

change the old lines to these:

```
       if step_type == 'mapper':
            child_args = (
                ['--mapper'] + ['"'] + [input_path] + common_args + ['"'])
        elif step_type == 'reducer':
            child_args = (
                ['--reducer'] + ['"'] + [input_path] + common_args + ['"'])
```

(so, just a quote " added to the params, finally)

Dunno if it's a proper way of doing things but it worked (at least).

Sorry - have no time to create a pull request etc. as we're on a deadline.

**Comment by davidmarin** [comment]
Yeah, there seem to be an number of people having trouble with Hadoop 2.4.0.

Not sure where the `-e` comes from; any chance you could tell me the value of `child_args`?

**Comment by davidmarin** [comment]
mrjob now works properly with Hadoop 2.4.0. Closing
