### ISSUE TITLE
Number of mappers on a single-node cluster

### ISSUE THREAD

**Issue by andr0s** [Yelp/mrjob#905]
Using Cloudera Manager 5 with Yarn 2 and a powerful instance from Digital Ocean with 12 cores. This is a simple 1-node cluster. But it should work relatively fast because it has a lot of RAM and CPUs and SSD.

Executing job like that:
python script.py -r hadoop --jobconf mapred.map.tasks=10 input_file.gz > output_file.

After the source file (a big gzip archive created by cat "somefile" | gzip -c > input_file.gz) has been pushed into DFS, I see that the server load is still really low, and cores are doing nothing. I see only 1 python process there, in htop, running my script with --step-num 0 --mapper arguments.

Isn't that extremely inefficient? How to, finally, run many mappers on 1 node?

**Comment by davidmarin** [comment]
Huh, how big is your file? Hadoop may have decided it's not worth the trouble to split it, and it'd rather leave those mappers/reducers ready for the next job.

I believe there's s jobconf that allows you to reduce the split size.
