### ISSUE TITLE
terminate_idle_job_flows is slow and causes race conditions

### ISSUE THREAD

**Issue by anusha-r** [Yelp/mrjob#910]
The terminate_idle_job_flows script does a 'fetch-job-flows' loop followed by a 'terminate' loop. 
In our case, we have so many job flows that fetching all of them (up to 2 months worth) takes about 5 mins. After this, when this script works on terminating job flows, we see some races.
Here's a explanation of the timeline of this race:
1. Minute # 1: Job flow killer picks up a currently idle jobflow as candidate and continues running its fetch-loop
2. Minute # 2: A mrjob picks this particular candidate as the job flow to use and starts running on the jobflow. It creates a lock on this job flow on S3 before proceeding.
3. Minute # 5: The terminate script finally finishes collecting all candidates and starts killing one by one. At this point, we treat a lock acquired within the past 1 minute as a valid lock but those older than that are ignored. 
Thus, the job which started using this job flow in step 2 (and whose lock is older than 1 min) is now killed.

Rather than do a 'fetch-all' followed by 'terminate-all', does it make sense for the job flow killer to do a 'fetch-kill-fetch-kill...' loop over its 2 month period? 
(For now, we are working around this issue by using a higher --max-mins-locked option on this script)

**Comment by davidmarin** [comment]
Oh, because the script takes longer than the "lock". Yeah, fetch-kill-fetch-kill seems like the solution.

**Comment by davidmarin** [comment]
The workaround for now is to run `terminate_idle_job_flows` with `--max-mins-locked <something bigger than 1>`

**Comment by zachm** [comment]
@davidmarin, I would assume that running multiple, concurrent idle jobflow killers could also exacerbate this problem, yes?

(While this does sound like a stupid question, it is based on a Very Real World Scenario unfortunately.)

**Comment by davidmarin** [comment]
Offhand, I don't see how that would matter. The only way I can see it being an issue is if you only set `--max-minutes-locked` for one and the others were using the default (one minute).

**Comment by davidmarin** [comment]
Or if they were completely eating up your EMR API limit, making the time between listing the job flows and terminating them even longer than you expected...

**Comment by davidmarin** [comment]
Taking on this ticket
