### ISSUE TITLE
Filter input by filename

### ISSUE THREAD

**Issue by Fandekasp** [Yelp/mrjob#914]
Hello,

MrJob has a method [mapper-pre-filter](http://mrjob.readthedocs.org/en/latest/job.html#mrjob.job.MRJob.mapper_pre_filter) to filter the input line by line, but I would like to filter filenames and avoid having irrelevant files from a s3 bucket being read by emr.

How would you do that?

Also, I understand that mrjob is capable of opening gz files, but I also have tar directories, which I would like mrjob to open, then extract the relevant gz file from it and pass it as input. Is that somehow possible?

Thank you for your help!

**Comment by davidmarin** [comment]
It's do-able on the Python side; we could `ls()` the files, and then filter them by path. Not convinced this is super-useful, but if you implement something, I'll do my best to include it.

**Comment by davidmarin** [comment]
You could do this with a glob. If you're using `mapper_raw`, mrjob will process the glob for you (otherwise it'll get passed to Hadoop).
