### ISSUE TITLE
Distinguish tasks sharing the same emr job flow

### ISSUE THREAD

**Issue by smallredbean** [Yelp/mrjob#915]
When multiple tasks share the same emr job flow, the cluster itself seems not able to distinguish each of them. The distinguishing feature can be useful; for example, we use diamond to stream out system metrics to our own graphite cluster. We'd like to identify which time period associates to which task, instead of only to the (higher) job flow level.

One simple solution is to export runner._job_name to an environment variable using "-cmdenv". In this way, setup scripts can read the environment variable to configure the cluster (or, applications running on the cluster) accordingly.

Was wondering if this sounds like a feasible patch?

**Comment by davidmarin** [comment]
@smallredbean, does your `export_job_name` feature solve this?

**Comment by davidmarin** [comment]
Just wanted to point out that you can get the job name already like this:

```
mrjob.compat.jobconf_from_env('mapreduce.job.name')
```

**Comment by davidmarin** [comment]
Oh, the jobconf value is not the same as `self._job_name` (it's confusing, see #982).

Let's talk over your use case some day when we're both in the Yelp office. I'm hoping we can find a solution that doesn't require building new features.

**Comment by smallredbean** [comment]
Of course! We'd love to retrieve the running job identification with minimal poking to mrjob if it can be done on the hadoop level.

**Comment by davidmarin** [comment]
Talked to @smallredbean in person. Basically, mrjob feeds nice, human-readable information about the job into the EMR API, and the question is if any of this information is visible from the actual mapper/reducer that runs on Hadoop. Going to investigate!

**Comment by davidmarin** [comment]
Here's how you do it:

Your mrjob script has to upload a copy of itself to S3, and it will put it in a tmp dir containing a unique key belonging to the job. Inside the script, this path appears in the environment variable `tmpfiles` (along with any other files you've instructed mrjob to put in the job's working directory). Example:

```
s3://mrjob-95ea4d0c0a011ab6/tmp/mr_environ.davidmarin.20150407.190017.539128/files/mr_environ.py#mr_environ.py
```

The part you want is `mr_environ.davidmarin.20150407.190017.539128`.
