### ISSUE TITLE
EMR from Windows; SSH tunnel doesn't exist

### ISSUE THREAD

**Issue by davidmanheim** [Yelp/mrjob#919]
Whenever I run a EMR job from Windows, it attempts the following:
"Opening ssh tunnel to Hadoop job tracker"

Of course, in windows, by default, there is no command line SSH tool, so the connect fails - but the job still runs fine. 

There seems to be no way to ask it not to monitor the job, so this seems like a bug. Can we get a default of not trying to connect in Windows, or at least an option?

Error when trying to connect:

>Opening ssh tunnel to Hadoop job tracker
>Attempting to terminate job...
>Traceback (most recent call last):
>  File "[My MrJob Script.py]", line 52, in <module>
>    MRTweetHeaders.run()
>  File "C:\Python27\lib\site-packages\mrjob\job.py", line 494, in run
>    mr_job.execute()
>  File "C:\Python27\lib\site-packages\mrjob\job.py", line 512, in execute
>    super(MRJob, self).execute()
>  File "C:\Python27\lib\site-packages\mrjob\launch.py", line 147, in execute
>    self.run_job()
>  File "C:\Python27\lib\site-packages\mrjob\launch.py", line 213, in run_job
>    self.stdout.flush()
>  File "C:\Python27\lib\site-packages\mrjob\runner.py", line 615, in __exit__
>    self.cleanup()
>  File "C:\Python27\lib\site-packages\mrjob\emr.py", line 1010, in cleanup
>    super(EMRJobRunner, self).cleanup(mode=mode)
>  File "C:\Python27\lib\site-packages\mrjob\runner.py", line 561, in cleanup self._cleanup_job()
>  File "C:\Python27\lib\site-packages\mrjob\emr.py", line 1084, in _cleanup_job self._opts['ec2_key_pair_file'])
>  File "C:\Python27\lib\site-packages\mrjob\ssh.py", line 200, in ssh_terminate_single_job
>    ssh_bin, address, ec2_key_pair_file, ['hadoop', 'job', '-list']))
>  File "C:\Python27\lib\site-packages\mrjob\ssh.py", line 82, in ssh_run
>    p = Popen(args, stdout=PIPE, stderr=PIPE, stdin=PIPE)
>  File "C:\Python27\lib\subprocess.py", line 709, in __init__
>    errread, errwrite)
>  File "C:\Python27\lib\subprocess.py", line 957, in _execute_child
>    startupinfo)
>WindowsError: [Error 2] The system cannot find the file specified

**Comment by davidmarin** [comment]
The default *is* not to use SSH. Closing.
