### ISSUE TITLE
Hadoop 2.4.0

### ISSUE THREAD

**Issue by danjamker** [Yelp/mrjob#923]
Hi, 

I am running into issues when running MRJob on Hadoop 2.4.0. When it is trying to create the tmp directories on the HDFS it fails. I think this is due to to the use of the mkdir not mkdir -p.

**Comment by davidmarin** [comment]
This is fixed in `master` and will be in the next release

**Comment by davidmarin** [comment]
Moving this to v0.4.4 in the interest of getting a release out soon. We're keenly aware of mrjob's problems with newer versions of Hadoop; this is our first priority after the release.

**Comment by davidmarin** [comment]
Though the patch for mkdir has been pulled into `master`. If that fixes it, please close this issue.

**Comment by davidmarin** [comment]
Actually, assuming that this was fixed by the `mkdir -p` pull request. Please reopen if not.
