### ISSUE TITLE
Documentation Virtual Env

### ISSUE THREAD

**Issue by danjamker** [Yelp/mrjob#924]
Hi, 

Been working through the documentation for running mrjob with virtual env.

The code I think should be:

    - if [ ! -d $VENV ]; then virtualenv $VENV --system-site-packages; fi
    - . $VENV/bin/activate

As this would check to see if the dict for the env exists, as -e is for a file. Also it needs to check to see if it does not exist so it can create the environment.

Not sure where to put this edit.

**Comment by davidmarin** [comment]
Thanks for your concern, but `-e` actually matches any type of file; it's `-f` for "regular" files.
