### ISSUE TITLE
how to record log during MapReduce？

### ISSUE THREAD

**Issue by William-Sang** [Yelp/mrjob#927]
thanks for your great work, and i'm ussing MRJob with EMR to process trade records.
because the raw data may be imcomplete( lose some fields). and i need to log these records, and at the meantime continue to progress the rest.

The question is that I don't know how to log during MapReduce in EMR.

Thanks for your time. I need your help~

**Comment by davidmarin** [comment]
That is very awkward, but this is more of a question than an issue.
