### ISSUE TITLE
ValueError('No closing quotation') raised for comment lines

### ISSUE THREAD

**Issue by akonradi** [Yelp/mrjob#928]
I've got a script that installs some dependencies on EMR, so I wrote a wrapper that takes a block of bash, splits it into lines, and passes these to the `--setup` command. Some of these lines are comments, and I ran into a bug today when one of the comment lines contained an apostrophe, which caused MRJob to raise a ValueError. I've been able to reproduce the bug without my wrapper script; running the following for a simple test job raises the same error:

```
mrjob run test.py --setup "# I'm sure this is a comment"
```

**Comment by davidmarin** [comment]
This appears to have been fixed.
