### ISSUE TITLE
Will oddjob support hadoop 2.x.x  

### ISSUE THREAD

**Issue by William-Sang** [Yelp/mrjob#937]
Will oddjob support hadoop 2.x.x  
@jblomo I can't figure out without oddjob how to write into subfolders in emr.
thanks for your time and attention.

**Comment by kkazlowski** [comment]
Ping. Has there been any progress on getting oddjob to support Hadoop 2? Having some trouble with deprecated versions of Amazon's EMR AMI that support Hadoop 1, close to forcing us to move to Hadoop 2, and we use the `oddjob.MultipleValueOutputFormat`.

**Comment by davidmarin** [comment]
I don't think so, but thank you for letting me know this is a priority for you.

mrjob v0.5.0, which supports the newer AMIs and Hadoop 2 better, and after that I'll have time to working on input/output format-related issues. Plus working on oddjob would be a good excuse to learn Clojure. :)

**Comment by davidmarin** [comment]
Just curious, the 2.4.11 AMI doesn't work for you? I don't think EMR is trying to phase out Hadoop 1 entirely.

**Comment by kkazlowski** [comment]
We're trying out 2.4.11, but that's still using Debian Squeeze, which is EOL as of Feb 29, 2016; we're already having some trouble with mirrors on fetching packages. So it's unclear how long that's going to last. 

Thanks David.

**Comment by davidmarin** [comment]
Ah yes, just got the email from AWS.

**Comment by kkazlowski** [comment]
FYI it looks like there's https://empiricalresults.github.io/nicknack/ which appears to be roughly oddjob intended for Hadoop 2.4. Still working on getting our other stuff to work on Hadoop 2 via newer AMI's, but this looks promising, and wanted to share as this may be the solution for others here who have a need.

**Comment by jblomo** [comment]
I love that the naming convention has continued!  Thanks for the update,
let us know how it goes!

**Comment by kkazlowski** [comment]
Oh yeah, went quiet here, but was able to convert our use of oddjob.MultipleValeOutputFormat -> nicknack.MultipleValueOutputFormat just fine. (Some other issues with migrating to the newer AMI's, but that's unrelated.)

**Comment by davidmarin** [comment]
Great!

Would love to hear about AMI migration issues. Yelp is going to need to migrate off 2.x eventually. Are you using mrjob 0.4.6, or the version in `master`?

**Comment by kkazlowski** [comment]
Our issues were almost entirely around migrating from Debian -> Amazon Linux (finding the right packages and changing our `setup` and `bootstrap` for the different Linux distro). Migrating Hadoop 1 -> 2.4 didn't seem to be much of an issue, other than job trackers working differently and our setup for that breaking, but that's less than timely. 

We were using a fork of mrjob 0.4.4 to have some custom job tracker code of our own.

**Comment by rirwin** [comment]
Another roadblock is python 2.7.  We'd have to re-employ a solution for
install python 2.7 during the setup phase.  I'm really not sure why amazon
linux doesn't have this.  Has anyone reached out to them and asked why?

Ryan Irwin

**Comment by kkazlowski** [comment]
Yeah python2.7-related issues were the major friction for me. We had a setup for this for Debian and it changed quite a bit for Amazon Linux. I was surprised that even their newest machines only have Python2.6.9. 

I can share our steps for `bootstrap` (and maybe `setup` too, I forget) for Python2.7 setup if you want @rirwin

**Comment by rirwin** [comment]
That would be fantastic!  Thanks @kkazlowski!

Ryan Irwin

**Comment by kkazlowski** [comment]
@rirwin The relevant section of our mrjob.conf below. Note that if you don't use easy_install-2.7/pip2.7, it will install packages for Python2.6 instead. I still have this `python_bin` key around from when I did this for Hadoop1, and not sure it's necessary, but in case. 

```
    bootstrap:
      # Install Python2.7
      - wget -S -T 10 -t 5 https://www.python.org/ftp/python/2.7.6/Python-2.7.6.tgz
      - tar xvfz Python-2.7.6.tgz
      - cd Python-2.7.6
      - ./configure && make && sudo make install
      - cd ..
      - sudo rm /usr/local/bin/python && sudo ln -s /usr/local/bin/python2.7 /usr/local/bin/python
      # End Python2.7 Install. Install pip - yum install won't work
      - wget -S -T 10 -t 5 https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
      - sudo /usr/local/bin/python2.7 ez_setup.py
      - sudo /usr/local/bin/easy_install-2.7 pip
      # We must use easy_install-2.7 and pip2.7 to specifically install packages for Python2.7, otherwise we get them for Python2.6
      - sudo easy_install-2.7 pytz==2015.4
      - sudo /usr/local/bin/pip2.7 install mrjob==0.4.4
      ...
    python_bin: python  # Make this config work in Python 3 too
```

**Comment by benjolitz** [comment]
I used MrJob several months ago to bootstrap a PyPy install.

Doing that got my job runtime down to that of an equivalent Java implementation (segmenting log files)

Ben

**Comment by rirwin** [comment]
@kkazlowski That looks great!  I look forward to trying that out or trying
something similar soon.

@ben Nice suggestion! I hadn't thought about trying that for MRJob.

Ryan Irwin

**Comment by davidmarin** [comment]
@benjolitz great to hear that using PyPy really did speed things up. I suspected it would, but haven't gotten around to trying it.

At some point, I'm going to work on getting mrjob to work as smoothly with PyPy as it does with CPython (see #1011); when I do; would you be up for answering questions and testing things out?
