### ISSUE TITLE
User should be able to specify the name of the job

### ISSUE THREAD

**Issue by david-cliqz** [Yelp/mrjob#955]
Currently jobs are assigned an auto-generated, unique name. While that is fine, users should be able to override this and give descriptive names to their jobs.

**Comment by davidmarin** [comment]
Looking at this more, mrjob wasn't build with setting the job name in mind. For example, the Hadoop runner assumes `self._job_name` is unique, and uses it to set the job's temp directory.

I don't think this is a bad idea, but mrjob isn't ready for it yet. Backing out your change for now.

**Comment by davidmarin** [comment]
There is a `--label` option that pretty much does this.
